import { ProjectItem } from './types';

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: 'nile-ritz-carlton-presidential-suites',
    title: 'The Nile Ritz-Carlton Presidential Suites',
    titleAR: 'أجنحة النيل ريتز-كارلتون الرئاسية والصالون الملكي',
    slug: 'nile-ritz-carlton-presidential-suites',
    location: 'Cairo, Egypt',
    projectType: 'Hotel',
    year: '2023',
    shortDescription: 'Monumental pierced brass chandeliers, hand-hammered wall sconces, and custom architectural brass door hardware for royal suites overlooking the Nile.',
    description: 'TURATH was commissioned to engineer, fabricate, and install custom decorative and architectural brass installations across the presidential suites and grand VIP reception halls overlooking the River Nile. Every fixture reflects classical Mamluk geometry translated into contemporary luxury proportions, casting hypnotic shadow patterns that illuminate high-end Egyptian hospitality.',
    craftStory: 'Hundreds of hours of manual repoussé and precision punch-needle perforation were performed by Cairo’s master craftsmen in historic Al-Gamaliya. Seamless hidden structural steel armatures ensure monumental weight-bearing safety while maintaining delicate artisanal filigree aesthetics.',
    materials: 'Solid High-Grade Egyptian Yellow Brass, Hand-Oxidized Acid Patina, High-Clarity Beveled Mirrors, Internal Steel Rigging',
    finish: 'Antique Hand-Burnished Brass with Protective Microcrystalline Wax',
    workDelivered: [
      '4x Monumental Tiered Sultan Hassan Perforated Chandeliers (180 cm diameter)',
      '24x Hand-Pierced Geometric Wall Appliques with Warm LED Diffusion',
      '8x Custom Grand Archway Mirrors with Openwork Filigree Crests',
      '12x Solid Cast Brass Double Door Handles and Lock Escutcheons',
      'Custom Brass Decorative Grille Panels for Concealed HVAC Vents'
    ],
    customManufacturing: 'Custom engineering for reinforced seismic and vibration-damped ceiling mounts with dual stainless-steel safety cables. On-site technical assembly and balancing performed by TURATH master artisans.',
    coverImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1400&q=80',
    mediaType: 'image',
    coverRatio: '16:9',
    coverFit: 'cover',
    coverPosition: 'center',
    gallery: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/n51TrE7f17I',
    videoRatio: '16:9',
    videoFit: 'cover',
    relatedProductIds: ['turath-chandelier-01', 'TR-MIR-002', 'turath-mirror-01'],
    published: true,
    sortOrder: 1,
    seoTitle: 'The Nile Ritz-Carlton Presidential Suites | TURATH Architectural Projects',
    metaDescription: 'Custom handcrafted brass chandeliers, mirrors, and architectural lighting engineered by TURATH for The Nile Ritz-Carlton luxury presidential suites in Cairo.',
    createdAt: '2023-11-15T10:00:00Z',
    updatedAt: '2024-01-20T12:00:00Z',
  },
  {
    id: 'bab-al-qasr-royal-majlis',
    title: 'Bab Al-Qasr Palace Private Majlis & Dining Pavilion',
    titleAR: 'مجلس وقصر باب القصر الملكي وجناح الضيافة الفاخر',
    slug: 'bab-al-qasr-royal-majlis',
    location: 'Riyadh, Saudi Arabia',
    projectType: 'Palace',
    year: '2024',
    shortDescription: 'Complete custom metalwork fit-out including hand-hammered Siniya brass tables, pierced floor lanterns, and monumental foyer consoles.',
    description: 'A comprehensive custom brass fit-out for a 1,200 sq. meter royal reception majlis and private banquet pavilion. Designed in close collaboration with leading heritage interior architects to harmonize seamlessly with bookmatched Italian marble flooring, hand-woven silks, and soaring decorative timber ceilings.',
    craftStory: 'Classical Arabesque chisel engraving (Naqsh) executed entirely by hand over 3mm thick solid brass plates, followed by artisanal metal spinning of massive fluted urns. Each table base underwent five cycles of manual burnishing to achieve a deep, regal luster.',
    materials: 'Pure Egyptian Yellow Brass, Red Copper Inlays, Nero Marquina Marble Tops',
    finish: 'Warm Polished Gold Brass with Hand-Rubbed Satin Lacquer',
    workDelivered: [
      '6x Siniya Hand-Hammered Low Brass Tables (140 cm diameter)',
      '2x Monumental Foyer Consoles with Hand-Cut Islamic Filigree Aprons',
      '16x Pierced Mashrabiya Floor Lanterns with Intricate Shadow Geometry',
      '2x Grand Hand-Beaten Ceremonial Copper Incense Burners (Mabkhara)',
      'Handcrafted Brass Base Plates for Bespoke Dining Table Installations'
    ],
    customManufacturing: 'Custom structural sizing engineered directly from architectural CAD and Revit models; precision laser-assisted internal substructure clad with hand-worked 2.5mm brass sheeting.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80',
    mediaType: 'image',
    coverRatio: '16:9',
    coverFit: 'cover',
    coverPosition: 'center',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/ytBFnWnjw7Q',
    videoRatio: '16:9',
    videoFit: 'cover',
    relatedProductIds: ['turath-table-01', 'turath-table-02', 'turath-console-01'],
    published: true,
    sortOrder: 2,
    seoTitle: 'Bab Al-Qasr Royal Majlis & Pavilion | TURATH Custom Metalwork',
    metaDescription: 'Luxury palace majlis fit-out featuring hand-hammered brass tables, pierced floor lanterns, and bespoke consoles manufactured by TURATH in Riyadh.',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-03-01T12:00:00Z',
  },
  {
    id: 'zaytouna-waterfront-lounge',
    title: 'Zaytouna Waterfront Luxury Restaurant & Lounge',
    titleAR: 'مطعم ولاونج زيتونة الفاخر على الواجهة البحرية',
    slug: 'zaytouna-waterfront-lounge',
    location: 'Dubai Marina, UAE',
    projectType: 'Restaurant',
    year: '2023',
    shortDescription: 'Ceiling-suspended undulating brass light sculpture, custom hammered cocktail bar cladding, and bespoke tabletop brass lanterns.',
    description: 'An experiential high-end dining destination centered around ambient warmth and authentic Egyptian metalcraft. Over 60 custom fixtures cast delicate geometric shadows across the indoor dining salons and waterfront terrace, turning the evening dining experience into an intimate sanctuary.',
    craftStory: 'Micro-perforated brass sheet forming with laser-calibrated balance, followed by multi-stage chemical acid patination developed specifically to resist marine atmospheric humidity and salt mist.',
    materials: 'Marine-Grade Sealed Solid Brass, Pure Red Copper, Heat-Resistant Opal Glass Diffusers',
    finish: 'Dark Aged Antique Brass with Protective UV and Coastal Salt-Resistant Clear Coat',
    workDelivered: [
      '1x Continuous 18-Meter Suspended Undulating Brass Ribbon Chandelier',
      '35x Tabletop Rechargeable Cordless Brass Lanterns with Touch Dimming',
      '1x Hand-Hammered Brass Cocktail Bar Facade (12 meters long)',
      '18x Fluted Ambient Wall Sconces with Arabesque Pattern Cutouts'
    ],
    customManufacturing: 'Complete coastal weatherproofing, thermal shock-resistant glass housings, and certified wind-load mounting hardware for the open-air marina terrace.',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80',
    mediaType: 'image',
    coverRatio: '16:9',
    coverFit: 'cover',
    coverPosition: 'center',
    gallery: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/n51TrE7f17I',
    videoRatio: '16:9',
    videoFit: 'cover',
    relatedProductIds: ['turath-chandelier-01', 'TR-LGT-002'],
    published: true,
    sortOrder: 3,
    seoTitle: 'Zaytouna Waterfront Restaurant | TURATH Hospitality Metalwork',
    metaDescription: 'Handcrafted architectural brass installations, bar cladding, and bespoke lighting manufactured by TURATH for Zaytouna in Dubai Marina.',
    createdAt: '2023-08-20T10:00:00Z',
    updatedAt: '2023-10-15T12:00:00Z',
  },
  {
    id: 'villa-al-andalus-private-residence',
    title: 'Villa Al-Andalus Private Residence',
    titleAR: 'فيلا الأندلس السكنية الخاصة - القاهرة الجديدة',
    slug: 'villa-al-andalus-private-residence',
    location: 'New Cairo, Egypt',
    projectType: 'Villa',
    year: '2024',
    shortDescription: 'Complete artisanal brass architectural package: sweeping curved staircase balustrade, bespoke grand atrium chandelier, and arched vanity mirrors.',
    description: 'A bespoke residential masterpiece blending Andalusian architectural motifs with traditional Egyptian brass-smithing excellence. Every metal component was custom designed, engineered, and hand-finished from scratch for this private family estate.',
    craftStory: 'Hand-forged solid brass balusters meticulously hot-bent on custom wooden templates, assembled with hand-turned bronze finials. The central 3-meter chandelier features 36 individual pierced brass oil-lamp replicas electrified with modern energy-efficient filaments.',
    materials: 'Solid Forged Brass, Cast Bronze Finials, Antique Mirror Glass, Heavy Wall Brass Tubing',
    finish: 'Polished Heritage Brass with Soft Warm Champagne Wax Finish',
    workDelivered: [
      '45 Linear Meters of Hand-Forged Brass Curved Staircase Handrails & Balustrades',
      '1x Grand 3-Meter Atrium Chandelier with 36 Lighting Arms',
      '6x Custom Arched Mihrab Bathroom Mirrors with Hand-Pierced Openwork Crests',
      '14x Custom Bedroom Wall Sconces with Opal Glass Shades',
      '4x Double Entry Door Solid Brass Handles with Hand-Engraved Arabesque Borders'
    ],
    customManufacturing: '3D laser site scanning was utilized to capture exact millimeter curvatures of the sweeping spiral staircase, ensuring flawless on-site fitment without visible welds or seams.',
    coverImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80',
    mediaType: 'image',
    coverRatio: '16:9',
    coverFit: 'cover',
    coverPosition: 'center',
    gallery: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80'
    ],
    relatedProductIds: ['TR-MIR-002', 'turath-mirror-01', 'turath-chandelier-01'],
    published: true,
    sortOrder: 4,
    seoTitle: 'Villa Al-Andalus Private Residence | TURATH Bespoke Architecture',
    metaDescription: 'Hand-forged brass staircase balustrades, monumental chandeliers, and bespoke mirrors handcrafted by TURATH for a luxury villa in New Cairo.',
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-04-05T12:00:00Z',
  },
  {
    id: 'the-khedivial-boardroom-heritage-bank',
    title: 'The Khedivial Boardroom & Executive Headquarters',
    titleAR: 'قاعة الخديوي ومقر الإدارة التنفيذية المصرفية',
    slug: 'the-khedivial-boardroom-heritage-bank',
    location: 'Downtown Cairo, Egypt',
    projectType: 'Commercial',
    year: '2023',
    shortDescription: 'Restoration and bespoke fabrication of historic brass meeting table trim, engraved partition screens, and architectural wall sconces.',
    description: 'Commissioned to create heritage-grade architectural brass accents for the executive headquarters and historic boardroom of a prominent regional financial institution. The design pays homage to late 19th-century Khedivial Cairo architecture, using authentic hot-rolled brass profiles and museum-grade hand finishes.',
    craftStory: 'Precision hand-chiseling combined with classical lap joints and concealed fasteners. Every panel underwent five stages of aging to perfectly match the 120-year-old architectural woodwork.',
    materials: 'High-Purity Brass Alloy, Solid Red Copper Rivets, Toughened Bronze Glass',
    finish: 'Historic Dark Statuary Bronze Patina with Hand-Waxed Luster',
    workDelivered: [
      '1x 10-Meter Solid Brass Inlaid Boardroom Table Border & Cable Access Portals',
      '8x Geometric Arabesque Brass Partition Screens (2.4m height)',
      '16x Classical Khedivial Double-Arm Wall Appliques',
      'Solid Brass Executive Desk Nameplates and Signage Package'
    ],
    customManufacturing: 'Integrated low-voltage power conduits and seamless motorized screen housings hidden behind ornamental brass grilles.',
    coverImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=80',
    mediaType: 'image',
    coverRatio: '16:9',
    coverFit: 'cover',
    coverPosition: 'center',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80'
    ],
    relatedProductIds: ['turath-console-01', 'TR-LGT-002'],
    published: true,
    sortOrder: 5,
    seoTitle: 'The Khedivial Boardroom | TURATH Commercial Brass Projects',
    metaDescription: 'Historic brass partition screens, executive boardroom fittings, and architectural lighting crafted by TURATH in Downtown Cairo.',
    createdAt: '2023-06-18T10:00:00Z',
    updatedAt: '2023-09-10T12:00:00Z',
  }
];
