import { ProductCategoryInfo, ProductItem } from './types';

export const PRODUCT_CATEGORIES: ProductCategoryInfo[] = [
  {
    id: 'mirrors',
    name: 'MIRRORS',
    nameArabic: 'مرايا نحاسية',
    shortDesc: 'Handcrafted sunburst, arched, and geometric brass mirrors.',
    description: 'Artisanal Egyptian brass framed mirrors combining hand-hammered repoussé techniques, intricate openwork filigree, and polished bevel glass.',
    coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
    coverMediaType: 'video',
    coverVideoUrl: 'https://www.youtube-nocookie.com/embed/n51TrE7f17I',
    iconName: 'Sparkles',
  },
  {
    id: 'lighting',
    name: 'LIGHTING',
    nameArabic: 'إضاءة وثريات وأبليكات',
    shortDesc: 'Monumental pierced brass chandeliers, lanterns & architectural sconces.',
    description: 'Sculptural Egyptian brass chandeliers, hand-cut Gamaliya lanterns, and warm ambient appliques casting mesmerizing Islamic arabesque shadow patterns.',
    coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
    coverMediaType: 'video',
    coverVideoUrl: 'https://www.youtube-nocookie.com/embed/ytBFnWnjw7Q',
    iconName: 'Flame',
  },
  {
    id: 'tables',
    name: 'TABLES',
    nameArabic: 'طاولات نحاسية',
    shortDesc: 'Hand-engraved brass coffee tables, side tables & dining bases.',
    description: 'Solid brass structural bases, hand-hammered brass tray tables (Siniya), and architectural tables paired with luxury marble or tempered glass.',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Layers',
  },
  {
    id: 'consoles',
    name: 'CONSOLES',
    nameArabic: 'كونسول نحاسي فاخر',
    shortDesc: 'Monumental entryway consoles and handcrafted brass architectural foyer tables.',
    description: 'Solid forged brass frames, intricate openwork geometric aprons, and polished brass consoles paired with Egyptian alabaster, Nero Marquina marble, or tempered glass.',
    coverImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Crown',
  },
  {
    id: 'vases',
    name: 'VASES',
    nameArabic: 'فازات وأواني نحاسية',
    shortDesc: 'Chiseled brass floor vases, fluted urns, and decorative amphoras.',
    description: 'Hand-spun and hand-engraved Egyptian brass vases featuring classical Islamic patterns, fluted necks, and polished gold or dark antique finishes.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Wine',
  },
  {
    id: 'decorative-objects',
    name: 'DECORATIVE OBJECTS',
    nameArabic: 'مجسمات وقطع ديكور فنية',
    shortDesc: 'Hand-hammered serving trays, incense burners (Mabkhara) & luxury accents.',
    description: 'Refined lifestyle centerpieces, ceremonial brass burners, sculptured artifacts, candleholders, and etched trays made by master artisans.',
    coverImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Gem',
  },
  {
    id: 'handles',
    name: 'HANDLES',
    nameArabic: 'مقابض أبواب وخزائن',
    shortDesc: 'Solid cast brass palace door pulls, levers, and entry hardware.',
    description: 'Heavy architectural door pulls, traditional lion-head knockers, and bespoke forged brass levers that make every entrance unforgettable.',
    coverImage: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Key',
  },
  {
    id: 'handrails',
    name: 'HANDRAILS',
    nameArabic: 'درابزين وسلالم نحاسية',
    shortDesc: 'Architectural brass balustrades and custom handrail systems.',
    description: 'Precision-forged brass handrails, spiral balustrades, and geometric brass guardrails designed to client specifications for villas and hotels.',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    iconName: 'ShieldCheck',
  },
  {
    id: 'wall-cladding',
    name: 'WALL CLADDING',
    nameArabic: 'كسوة جدران وتجاليد نحاسية',
    shortDesc: 'Architectural brass wall cladding, textured panels & copper feature screens.',
    description: 'Custom-engineered brass wall cladding panels, hand-patinated tiles, mashrabiya brass screens, and architectural cladding for grand lobbies, feature walls, and luxury boutiques.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Grid',
  },
  {
    id: 'custom-pieces',
    name: 'CUSTOM PIECES',
    nameArabic: 'قطع مخصصة وتصنيع خاص',
    shortDesc: 'Bespoke metalwork tailored from your sketches, CAD, or drawings.',
    description: 'Full custom fabrication for architects and interior designers: feature metal installations, bespoke sculptural works, and one-of-a-kind architectural centerpieces.',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Wrench',
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // 1. Mirrors
  {
    id: 'turath-mirror-01',
    sku: 'TR-MIR-001',
    categoryId: 'mirrors',
    name: 'The Gamaliya Sunburst Brass Mirror',
    nameEN: 'The Gamaliya Sunburst Brass Mirror',
    nameAR: 'مرآة شعاع الشمس النحاسية - الجمالية',
    tagline: 'Hand-chiseled radial petals in antique golden brass',
    shortDescEN: 'Hand-chiseled radial petals in antique golden brass',
    shortDescAR: 'بتلات دائرية منحوتة يدويًا من النحاس الأصفر المعتق',
    description: 'An iconic masterwork handcrafted in Gamaliya, Cairo. Over 48 individually hammered brass rays radiate around a beveled focal mirror, treated with an antique wax patina.',
    fullDescriptionEN: 'An iconic masterwork handcrafted in Gamaliya, Cairo. Over 48 individually hammered brass rays radiate around a beveled focal mirror, treated with an antique wax patina. Inspired by the architectural celestial motifs of historic Fatimid Cairo, each petal is manually textured using steel chisels and annealed over open coals to achieve rich golden depth.',
    fullDescriptionAR: 'تحفة فنية فريدة صُنعت يدويًا في حي الجمالية بالقاهرة التاريخية. أكثر من 48 شعاعًا نحاسيًا مطروقًا يدويًا تتوزع حول مرآة مركزية مشطوفة الحواف معالجة بطبقة شمعية عتيقة. مستوحاة من الزخارف الفاطمية التراثية، حيث يتم نقش كل بتلة بأزاميل فولاذية وتعتيقها بدرجات النحاس الذهبي الدافئ.',
    story: 'Forged in the shadow of Bab Zuweila by generational coppersmiths whose lineage preserves the Fatimid repoussé chiseling traditions.',
    mainImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'video',
    videoUrl: 'https://www.youtube-nocookie.com/embed/n51TrE7f17I',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Solid High-Grade Egyptian Yellow Brass, Beveled Glass Mirror',
    materialDetails: 'Heavy-gauge solid brass sheets (grade CuZn37) combined with 6mm Belgian beveled glass.',
    finish: 'Antique Patina Brass',
    finishOptions: ['Antique Brass', 'Polished Gold Brass', 'Dark Verdigris Patina'],
    finishDetails: 'Hand-rubbed jewelers wax over fire-patinated brass.',
    craftTechnique: 'Chased Repoussé & Hand-Polishing',
    techniqueDetails: 'Individual petal repoussé chasing, silver-soldered ring frame, and micro-bevel mirror mounting.',
    dimensions: '110 cm Diameter x 6 cm Depth',
    diameter: '110 cm',
    depth: '6 cm',
    weight: '14.5 kg',
    customDimensions: 'Available from 80 cm up to 200 cm custom diameter.',
    customSize: 'Full custom sizing on request',
    customDesign: 'Ray count, inner medallion etching, and frame profile customizable',
    customFinish: 'Custom matte, antique, or 24K gold electroplated finish',
    availability: 'made_to_order',
    leadTime: '10-14 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'gamaliya-sunburst-brass-mirror',
    seoTitle: 'The Gamaliya Sunburst Brass Mirror | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian sunburst brass mirror featuring 48 individually chiseled brass petals and beveled mirror glass.',
    seoKeywords: 'brass mirror, sunburst mirror, Egyptian brass, Gamaliya, luxury mirror, handcrafted metalwork',
    whatsappMessage: 'Hello TURATH, I am interested in ordering: The Gamaliya Sunburst Brass Mirror (Product ID: TR-MIR-001). Please provide pricing and technical specifications.',
    categoryFields: {
      mirrorType: 'Sunburst Wall Mirror',
      mirrorShape: 'Round',
      frameMaterial: 'Solid Yellow Brass',
      frameTechnique: 'Hand-chiseled Repoussé',
      glassType: '6mm Clear Beveled Glass',
      mounting: 'Heavy-duty wall cleat included',
      orientation: 'Universal Round',
    },
  },
  {
    id: 'turath-mirror-02',
    sku: 'TR-MIR-002',
    categoryId: 'mirrors',
    name: 'Mamluk Arched Mihrab Mirror',
    nameEN: 'Mamluk Arched Mihrab Mirror',
    nameAR: 'مرآة المحراب المملوكي المقوسة',
    tagline: 'Pierced filigree crest with Islamic horseshoe arch',
    shortDescEN: 'Pierced filigree crest with Islamic horseshoe arch',
    shortDescAR: 'تاج مفرغ بدقة الأرابيسك مع قوس حدوة الحصان المملوكي',
    description: 'Inspired by the historic palaces of Al-Mu’izz street. The top arch features intricate pierced brass arabesques that gently filter lighting above the mirror glass.',
    fullDescriptionEN: 'Inspired by the historic palaces of Al-Mu’izz street. The top arch features intricate pierced brass arabesques that gently filter lighting above the mirror glass. Constructed with a heavy structural brass border and reinforced backing for monumental salon or entryway presence.',
    fullDescriptionAR: 'مستوحاة من قصور شارع المعز التاريخية. يتميز التاج العلوي بزخارف نباتية وهندسية إسلامية مفرغة يدويًا تسمح بنفاذ الضوء بنعومة، مع إطار نحاسي متين وهيكل مدعم ومناسب لمداخل الفلل والقصور وصالونات الاستقبال الفخمة.',
    story: 'Recreated from archival drawings of 14th-century Mamluk mosque portals in historic Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Solid 2mm Pierced Brass Plate, Antiqued Backing',
    materialDetails: '2.5mm solid brass plate with hand-sawn openwork crest.',
    finish: 'Aged Patina Brass',
    finishOptions: ['Antique Patina', 'Brushed Satin Gold', 'Burnished Bronze'],
    finishDetails: 'Chemically aged verdigris shadow tone with bright brass crest highlights.',
    craftTechnique: 'Openwork Piercing & Acid-Etched Borders',
    techniqueDetails: 'Pierced fretwork sawed by hand using jeweler bow-saws.',
    dimensions: '140 cm H x 80 cm W x 4 cm D',
    height: '140 cm',
    width: '80 cm',
    depth: '4 cm',
    weight: '18 kg',
    customDimensions: 'Custom heights available up to 260 cm for grand hotel foyers.',
    customSize: 'Custom dimensions available',
    customDesign: 'Arch geometry and calligraphy band customization available',
    customFinish: 'Bronze, satin, antique, or polished',
    availability: 'made_to_order',
    leadTime: '14-18 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Offices'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'mamluk-arched-mihrab-mirror',
    seoTitle: 'Mamluk Arched Mihrab Mirror | TURATH Egypt',
    metaDescription: 'Luxury Mamluk arched mirror with hand-pierced Islamic filigree crest in antique brass.',
    seoKeywords: 'Mamluk mirror, arched mirror, Islamic brass, Cairo filigree, handcrafted mirror',
    whatsappMessage: 'Hello TURATH, I am interested in ordering: Mamluk Arched Mihrab Mirror (Product ID: TR-MIR-002). Please provide quotation.',
    categoryFields: {
      mirrorType: 'Arched Vanity & Hallway Mirror',
      mirrorShape: 'Mihrab Horseshoe Arch',
      frameMaterial: 'Solid Brass Plate & Tube',
      frameTechnique: 'Hand-Pierced Openwork Arabesque',
      glassType: '5mm High Clarity Float Mirror',
      mounting: 'Double concealed z-bar wall brackets',
      orientation: 'Vertical Wall Mount',
    },
  },

  // 2. Lighting
  {
    id: 'turath-chandelier-01',
    sku: 'TR-CHND-001',
    categoryId: 'lighting',
    name: 'Sultan Hassan Monumental Pierced Chandelier',
    nameEN: 'Sultan Hassan Monumental Pierced Chandelier',
    nameAR: 'ثريا السلطان حسن المعمارية المخرمة',
    tagline: 'Multi-tier grand chandelier casting hypnotic star shadows',
    shortDescEN: 'Multi-tier grand chandelier casting hypnotic star shadows',
    shortDescAR: 'ثريا فخمة متعددة المستويات تعكس ظلالاً نجمية ساحرة',
    description: 'A breathtaking centerpiece designed for double-height entrances, palace salons, and boutique hotel lobbies. Tens of thousands of microscopic hand-punched perforations emit warm amber ambient light.',
    fullDescriptionEN: 'A monumental centerpiece designed for double-height entrances, palace salons, and luxury hotel lobbies. Tens of thousands of microscopic hand-punched perforations cast intricate arabesque shadow patterns across ceilings and walls, transforming the surrounding space into an ambient sanctuary.',
    fullDescriptionAR: 'تحفة إضاءة معمارية عملاقة مخصصة للمداخل المرتفعة وصالات القصور وبهو الفنادق الراقية. عشرات الآلاف من الثقوب الدقيقة المنقوشة يدويًا تعكس ظلالاً هندسية ساحرة وتمنح المكان أجواء دافئة مفعمة بالفخامة المصرية الأصيلة.',
    story: 'Modeled after the pierced brass oil lamps that hung in Cairo’s 14th-century Sultan Hassan Mosque.',
    mainImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Pure Heavy Egyptian Brass, Internal Warm LED Chandelier Cluster',
    materialDetails: 'Solid spun and rolled brass cones joined with internal steel suspension skeleton.',
    finish: 'Antique Burnished Brass',
    finishOptions: ['Antique Burnished Brass', 'Champagne Gold', 'Aged Oxidized Dark Brass'],
    finishDetails: 'Multi-stage acid burnishing and hand-waxed sealing.',
    craftTechnique: 'Hand-Pierced Perforated Brass (Mashrabiya Style)',
    techniqueDetails: 'Pierced with custom tempered steel punch needles, one perforation at a time.',
    dimensions: '180 cm H x 120 cm W (Custom sizing available)',
    height: '180 cm',
    width: '120 cm',
    diameter: '120 cm',
    weight: '38 kg',
    customDimensions: 'Custom diameters from 80 cm up to 300 cm available.',
    customSize: 'Tailored dimensions and drop heights available',
    customDesign: 'Tier configuration and pattern density tailored to architects blueprints',
    customFinish: 'Antique bronze, satin champagne, or polished mirror gold',
    availability: 'made_to_order',
    leadTime: '3-4 weeks',
    applications: ['Palaces', 'Villas', 'Hotels', 'Restaurants', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'sultan-hassan-monumental-chandelier',
    seoTitle: 'Sultan Hassan Monumental Pierced Chandelier | TURATH Egypt',
    metaDescription: 'Monumental Egyptian pierced brass chandelier creating 360-degree star shadows for luxury hospitality and villas.',
    seoKeywords: 'pierced brass chandelier, Islamic chandelier, Sultan Hassan, Cairo lighting, luxury lighting',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Sultan Hassan Monumental Chandelier (Product ID: TR-CHND-001). Please send catalog specs and quotation.',
    categoryFields: {
      chandelierType: 'Multi-Tier Pierced Pendant Chandelier',
      numberOfLights: '12 Lights (E27 Standard / LED Compatible)',
      bulbType: 'Warm White LED 2700K',
      voltage: '110V - 240V Universal',
      wattage: 'Max 60W per socket',
      bulbIncluded: true,
      suspensionType: 'Reinforced Solid Brass Heavy Link Chain & Ceiling Rose',
      suspensionLength: 'Adjustable up to 250 cm',
    },
  },
  {
    id: 'turath-chandelier-02',
    sku: 'TR-CHND-002',
    categoryId: 'lighting',
    name: 'Nile Lotus Pendant Chandelier',
    nameEN: 'Nile Lotus Pendant Chandelier',
    nameAR: 'ثريا لوتس النيل المتدلية',
    tagline: 'Contemporary brass dome with traditional chased interior',
    shortDescEN: 'Contemporary brass dome with traditional chased interior',
    shortDescAR: 'قبة نحاسية معاصرة مع باطن ذهبي مطروق يدويًا',
    description: 'Sleek brushed brass exterior with a richly hand-hammered gold leaf interior that provides exceptional warm downward task and mood illumination.',
    fullDescriptionEN: 'A master balance of clean modern architectural form and ancient Egyptian craftsmanship. The sleek spun brass outer shell contrasts with a dazzling interior chiseled and gold-leaf patinated to reflect warm downward illumination.',
    fullDescriptionAR: 'توازن ساحر بين التصميم المعماري المعاصر وأصالة الحرفة المصرية القديمة. هيكل خارجي أنيق مصقول بعناية يقابله تجويف داخلي مطروق يدويًا يعكس إضاءة ذهبية دافئة ومثالية لطاولات الطعام والجلسات الراقية.',
    story: 'Inspired by the sacred lotus bud rising from the Nile river, celebrated in Egyptian art for millennia.',
    mainImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Spun Brass Shell, Chased Golden Interior',
    materialDetails: 'Spun from single 3mm brass disc on historic Cairo metal lathes.',
    finish: 'Brushed Satin Gold',
    finishOptions: ['Two-Tone Matte Black & Gold Brass', 'Solid Polished Brass', 'Warm Antique Brass'],
    finishDetails: 'Brushed exterior with hand-dimpled gold luster interior.',
    craftTechnique: 'Metal Spinning & Chasing',
    techniqueDetails: 'Heavy spinning lathe shaping followed by thousands of ball-peen hammer strikes.',
    dimensions: '75 cm Diameter x 45 cm H',
    diameter: '75 cm',
    height: '45 cm',
    weight: '9.2 kg',
    customDimensions: 'Diameters from 40 cm to 110 cm available.',
    customSize: 'Single or cluster configurations available',
    customDesign: 'Custom outer finishes (black patina, brushed brass, verdigris)',
    customFinish: 'Custom finish options available',
    availability: 'in_stock',
    leadTime: '10-12 business days',
    applications: ['Homes', 'Villas', 'Restaurants', 'Hotels', 'Offices', 'Interior Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'nile-lotus-pendant-chandelier',
    seoTitle: 'Nile Lotus Pendant Chandelier | TURATH Egypt',
    metaDescription: 'Modern spun brass pendant chandelier with hand-chased interior gold leaf reflection.',
    seoKeywords: 'brass pendant, lotus chandelier, dining light, Egyptian brass fixture, luxury pendant',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Nile Lotus Pendant (Product ID: TR-CHND-002). Please send quote.',
    categoryFields: {
      chandelierType: 'Single Dome Pendant Light',
      numberOfLights: '3 Cluster Sockets (E27)',
      bulbType: 'Warm White LED Filament',
      voltage: '110V - 240V',
      wattage: 'Max 40W per socket',
      bulbIncluded: true,
      suspensionType: 'Fabric Braided Cable & Solid Brass Rod',
      suspensionLength: '150 cm adjustable cord',
    },
  },

  // 3. Wall Lights (Appliques)
  {
    id: 'turath-applique-01',
    sku: 'TR-APPL-001',
    categoryId: 'lighting',
    name: 'Arabesque Lattice Shadow Sconce',
    nameEN: 'Arabesque Lattice Shadow Sconce',
    nameAR: 'أبليك الشبيكة الأرابيسك الجداري',
    tagline: 'Wall applique with 360-degree geometric shadow projection',
    shortDescEN: 'Wall applique with 360-degree geometric shadow projection',
    shortDescAR: 'أبليك جداري يعكس ظلالاً هندسية ثلاثية الأبعاد بزاوية 360 درجة',
    description: 'Mounted flush against the wall, this brass applique transforms hallways and living spaces into living geometric art installations when lit.',
    fullDescriptionEN: 'Mounted flush against the wall, this brass applique transforms corridors, salons, and suite entrances into radiant architectural displays. Precision hand-pierced arabesques project crisp geometric shadows across the wall surface.',
    fullDescriptionAR: 'يتم تركيبه مستويًا على الحائط ليحوّل الممرات والغرف إلى لوحة فنية ضوئية متكاملة. النقوش الأرابيسكية المفرغة يدويًا تعكس خطوطًا ضوئية هندسية ساحرة على الجدران تضفي دفئًا وأناقة لا مثيل لها.',
    story: 'Designed after the Mashrabiya window lattices of Beit El Suhaymi in historic Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Cut Brass Plate with Concealed Warm Sconce Socket (E27)',
    materialDetails: 'Solid brass curved shield with concealed aluminum mounting base.',
    finish: 'Antique Brass',
    finishOptions: ['Antique Brass', 'Raw Polished Gold', 'Hammered Patina'],
    finishDetails: 'Aged brass patina with sealed lacquer protectant.',
    craftTechnique: 'Pierced Geometric Filigree',
    techniqueDetails: 'Micro-pierced openwork using traditional Gamaliya hand saws.',
    dimensions: '60 cm H x 25 cm W x 14 cm D',
    height: '60 cm',
    width: '25 cm',
    depth: '14 cm',
    weight: '3.8 kg',
    customDimensions: 'Available in heights from 40 cm to 120 cm.',
    customSize: 'Custom size options available',
    customDesign: 'Pattern motif and projection angle customized for projects',
    customFinish: 'Satin gold, bronze, or aged verdigris',
    availability: 'in_stock',
    leadTime: '7-10 business days',
    applications: ['Homes', 'Villas', 'Hotels', 'Restaurants', 'Commercial Projects', 'Hospitality'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'arabesque-lattice-shadow-sconce',
    seoTitle: 'Arabesque Lattice Shadow Sconce | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian brass wall light sconce casting intricate arabesque shadows on walls.',
    seoKeywords: 'brass wall sconce, applique, Egyptian lighting, wall light, arabesque lighting',
    whatsappMessage: 'Hello TURATH, I would like to order the Arabesque Lattice Shadow Sconce (Product ID: TR-APPL-001). Please send pricing.',
    categoryFields: {
      lightType: 'Wall Applique / Sconce',
      numberOfBulbs: 1,
      bulbType: 'E27 Filament Bulb (Warm Amber)',
      lightDirection: 'Omnidirectional Wall Wash & Pierced Shadow Projection',
      projection: '14 cm from wall',
      lightingEffect: '360° Geometric Arabesque Shadow Cast',
    },
  },

  // 3. Tables
  {
    id: 'turath-table-01',
    sku: 'TR-TAB-001',
    categoryId: 'tables',
    name: 'Al-Azhar Hexagonal Brass Coffee Table',
    nameEN: 'Al-Azhar Hexagonal Brass Coffee Table',
    nameAR: 'طاولة القهوة السداسية النحاسية - الأزهر',
    tagline: 'Hand-engraved tray top resting on carved brass arch base',
    shortDescEN: 'Hand-engraved tray top resting on carved brass arch base',
    shortDescAR: 'صينية نحاسية منقوشة يدويًا تستند إلى قاعدة أقواس إسلامية سداسية',
    description: 'A statement coffee table featuring an authentic removable brass tray (siniya) intricately engraved with 8-fold Islamic rosettes, seated upon a solid brass interlocking base.',
    fullDescriptionEN: 'A statement coffee table featuring an authentic removable heavy brass tray (siniya) intricately hand-chiseled with 8-fold Islamic rosettes and calligraphic medallions, resting upon an interlocking solid brass arched leg base.',
    fullDescriptionAR: 'طاولة قهوة فاخرة تجمع بين صينية نحاسية ثقيلة قابلة للرفع منقوشة يدويًا بأشكال الزهور الهندسية والزخارف الإسلامية، وقاعدة نحاسية سداسية تتألف من أقواس معمارية مفرغة تمنح الغرفة طابع الفخامة الملكية.',
    story: 'Inspired by the historic Mamluk brass trays crafted for Al-Azhar courtyards and royal salons.',
    mainImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Heavy Gauge Solid Brass Sheet & Cast Base',
    materialDetails: 'Solid 3.5mm thick tray sheet with cast brass mortise-and-tenon leg structure.',
    finish: 'Antiqued Gold Brass',
    finishOptions: ['Antiqued Gold Brass', 'Satin Brushed Brass', 'Two-Tone Pewter & Brass'],
    finishDetails: 'Acid-etched background with polished raised relief surfaces.',
    craftTechnique: 'Hand-Engraving & Solid Metal Joinery',
    techniqueDetails: 'Engraved with hardened steel burins over weeks of artisan hand labor.',
    dimensions: '90 cm Diameter x 48 cm H',
    diameter: '90 cm',
    height: '48 cm',
    weight: '22 kg',
    customDimensions: 'Custom diameters from 60 cm to 140 cm.',
    customSize: 'Custom diameters and heights available',
    customDesign: 'Center medallion and leg arches customizable',
    customFinish: 'Antique, satin brushed, or two-tone',
    availability: 'made_to_order',
    leadTime: '15-20 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'al-azhar-hexagonal-brass-coffee-table',
    seoTitle: 'Al-Azhar Hexagonal Brass Coffee Table | TURATH Egypt',
    metaDescription: 'Hand-engraved Egyptian brass tray table with solid arched brass base for luxury living rooms.',
    seoKeywords: 'brass coffee table, Egyptian tray table, siniya table, Islamic furniture, luxury brass table',
    whatsappMessage: 'Hello TURATH, I am interested in the Al-Azhar Hexagonal Coffee Table (Product ID: TR-TAB-001). Please provide pricing details.',
    categoryFields: {
      tableType: 'Coffee Table / Tea Table',
      shape: 'Hexagonal / Round Tray',
      topMaterial: 'Hand-Engraved Heavy Brass Siniya',
      baseMaterial: 'Interlocking Cast & Pierced Brass Arches',
      glassMarbleType: 'Optional tempered protective glass top available',
    },
  },

  // 4. Consoles
  {
    id: 'turath-console-01',
    sku: 'TR-CSL-001',
    categoryId: 'consoles',
    name: 'Al-Muizz Grand Entryway Brass & Nero Marquina Console',
    nameEN: 'Al-Muizz Grand Entryway Brass & Nero Marquina Console',
    nameAR: 'كونسول المعز النحاسي الفاخر مع رخام نيرو ماركينا',
    tagline: 'Solid forged brass geometric frame paired with polished natural marble',
    shortDescEN: 'Solid forged brass geometric frame paired with polished natural marble',
    shortDescAR: 'هيكل نحاسي هندسي مصبوب يدويًا مع سطح رخام أسود نيرو ماركينا طبيعي مصقول',
    description: 'A grand luxury console table crafted for prestigious foyer entrances and palace corridors. Features hand-forged solid brass geometric structural legs and a hand-carved edge profile.',
    fullDescriptionEN: 'A grand architectural console table crafted for prestigious foyer entrances, luxury hotel receptions, and palace corridors. Features hand-forged solid brass interlocking geometric legs, hand-patinated golden brass accents, and a select slab of Spanish Nero Marquina marble or Egyptian Galala marble.',
    fullDescriptionAR: 'كونسول معماري فاخر مصمم للمداخل الملكية وردهات الفنادق الفاخرة وصالات الاستقبال الكبرى. يجمع بين قاعدة نحاسية هندسية مفرغة يدويًا بتشطيب ذهبي معتق وسطح رخامي فخم يضفي وقارًا وفخامة استثنائية.',
    story: 'Inspired by the monumental entrance gates and carved stone lintels along Cairo’s historic Al-Mu’izz street.',
    mainImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass & Natural Marble',
    materials: 'Solid High-Grade Egyptian Brass, Nero Marquina Black Marble Top',
    materialDetails: 'Solid 40x40mm brass tubular frame reinforced with welded internal gussets, 20mm beveled Spanish marble slab.',
    finish: 'Hand-Rubbed Antique Gold Brass',
    finishOptions: ['Hand-Rubbed Antique Gold', 'Mirror Polished Brass', 'Dark Smoked Bronze Patina'],
    finishDetails: 'Multi-layer microcrystalline wax seal over acid-patinated brass.',
    craftTechnique: 'Architectural Brass Forging & Precision Joinery',
    techniqueDetails: 'Precision miter joints, silver brazing, and hand-chiseled perimeter border details.',
    dimensions: '140 cm W x 42 cm D x 88 cm H',
    width: '140 cm',
    depth: '42 cm',
    height: '88 cm',
    weight: '48 kg',
    customDimensions: 'Custom widths available from 100 cm to 240 cm.',
    customSize: 'Custom dimensions and marble options available on request',
    customDesign: 'Leg profile, brass fretwork, and stone slab selection customizable',
    customFinish: 'Antique gold, brushed satin brass, or polished high-luster',
    availability: 'made_to_order',
    leadTime: '15-22 business days',
    applications: ['Palaces', 'Villas', 'Luxury Foyers', 'Hotels', 'VIP Salons'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'al-muizz-grand-entryway-brass-marble-console',
    seoTitle: 'Al-Muizz Grand Entryway Brass & Marble Console | TURATH Egypt',
    metaDescription: 'Luxury Egyptian solid brass console table with Nero Marquina marble top for grand foyers and palace entrances.',
    seoKeywords: 'brass console, luxury console table, Egyptian brass furniture, marble top console, foyer table',
    whatsappMessage: 'Hello TURATH, I am interested in the Al-Muizz Grand Entryway Brass Console (Product ID: TR-CSL-001). Please provide quotation and dimensions.',
    categoryFields: {
      consoleType: 'Architectural Foyer Console',
      legDesign: 'Interlocking Geometric Brass Arches',
      topMaterial: 'Natural Nero Marquina Marble Slab',
      baseMaterial: 'Solid Forged Brass Heavy Structure',
      mounting: 'Freestanding with optional wall-anchor bracket',
    },
  },

  // 5. Handles
  {
    id: 'turath-doorhandle-01',
    sku: 'TR-HDL-001',
    categoryId: 'handles',
    name: 'Imperial Palace Lion Head Solid Brass Pull',
    nameEN: 'Imperial Palace Lion Head Solid Brass Pull',
    nameAR: 'مقبض قصر الرئاسة برأس الأسد من النحاس الصب',
    tagline: 'Heavy sand-cast architectural entrance handle',
    shortDescEN: 'Heavy sand-cast architectural entrance handle',
    shortDescAR: 'مقبض مدخل رئيسي فاخر مصبوب من النحاس الخالص برأس أسد بارز',
    description: 'Weighing over 4.5 kilograms of solid cast brass, this statement handle is inspired by historic Egyptian palace portals. Features tactile detailed relief and durable weather-resistant wax finish.',
    fullDescriptionEN: 'Weighing over 4.5 kilograms of solid sand-cast brass, this monumental pull is designed for luxury villa and palace main entrance portals. Featuring high-relief lion head symbolism and a hand-turned reeded gripping bar with concealed through-bolt mounting.',
    fullDescriptionAR: 'يزن المقبض أكثر من 4.5 كيلوجرام من النحاس المصبوب الصلب، وهو مصمم خصيصًا لمداخل القصور والفلل الفاخرة. يتميز بنقوش بارزة ثلاثية الأبعاد تمثل رأس الأسد الملكي مع مقبض محزز مريح لليد وتثبيت مخفي قوي ومقاوم للعوامل الجوية.',
    story: 'Cast using traditional sand-molding techniques practiced in Cairo foundry alleys since Mamluk times.',
    mainImage: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Solid Cast Egyptian Brass Alloy',
    materialDetails: 'High-density sand-cast brass alloy with high copper content for weather resistance.',
    finish: 'Aged Antique Patina',
    finishOptions: ['Aged Antique Patina', 'Polished High-Luster Brass', 'Matte Architectural Bronze'],
    finishDetails: 'Thermal wax immersion for exterior weather protection.',
    craftTechnique: 'Sand-Casting & Hand-Chiseling',
    techniqueDetails: 'Sand molding, molten brass pouring, followed by hand chasing of mane details.',
    dimensions: '45 cm Length x 12 cm Width',
    height: '45 cm',
    width: '12 cm',
    depth: '9 cm',
    weight: '4.8 kg',
    customDimensions: 'Custom lengths from 30 cm up to 100 cm available.',
    customSize: 'Single or back-to-back pairs available',
    customDesign: 'Custom escutcheon plates and family crests cast on request',
    customFinish: 'Weatherproof exterior dark bronze or bright gold',
    availability: 'in_stock',
    leadTime: '10 business days',
    applications: ['Palaces', 'Villas', 'Hotels', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'imperial-palace-lion-head-brass-pull',
    seoTitle: 'Imperial Palace Lion Head Solid Brass Pull | TURATH Egypt',
    metaDescription: 'Solid cast brass entrance door handle pull with lion head relief for luxury villas and palaces.',
    seoKeywords: 'brass door pull, palace door handle, lion head handle, Egyptian brass hardware, luxury door pull',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Imperial Lion Head Door Pull (Product ID: TR-HDL-001). Please send quote.',
    categoryFields: {
      handleType: 'Entrance Door Pull Handle (Single or Back-to-Back Pair)',
      doorType: 'Solid Wood, Glass, or Heavy Metal Entrance Doors',
      backplate: 'Integrated Cast Medallion Rosettes',
      mountingType: 'Concealed Through-Bolt Fixings Included',
      lockCompatibility: 'Universal pull - compatible with mortise, deadbolt, or electronic smart locks',
    },
  },

  // 6. Handrails
  {
    id: 'turath-handrail-01',
    sku: 'TR-RAIL-001',
    categoryId: 'handrails',
    name: 'Bespoke Mashrabiya Brass Staircase Balustrade',
    nameEN: 'Bespoke Mashrabiya Brass Staircase Balustrade',
    nameAR: 'درابزين السلالم النحاسي المعماري - شبيكة المشربية',
    tagline: 'Continuous custom-fabricated architectural railing',
    shortDescEN: 'Continuous custom-fabricated architectural railing',
    shortDescAR: 'درابزين سلالم نحاسي معماري متصل بنقوش المشربية الإسلامية',
    description: 'Precision-welded solid brass architectural handrails and balusters featuring classical Islamic geometric patterns for luxury villas, duplexes, and prestigious hotels.',
    fullDescriptionEN: 'Continuous precision-engineered solid brass architectural balustrade system. Features waterjet-cut and hand-finished Mashrabiya geometric infill panels, molded solid brass top-cap profiles, and heavy turned brass newel posts designed to architects exact stair rise and run.',
    fullDescriptionAR: 'نظام درابزين معماري متكامل من النحاس الخالص المخصص للسلالم الداخلية الفاخرة. يجمع بين ألواح الشبيكة الهندسية المقطوعة بدقة والمشطوبة يدويًا، مع مقبض علوي انسيابي وقوائم متينة مصممة بدقة حسب المقاسات الهندسية للمشروع.',
    story: 'Engineered in our Cairo fabrication studio to blend traditional aesthetics with modern architectural safety codes.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Architectural Brass Box Profiles, Flat Bars & Turned Newel Posts',
    materialDetails: 'C36000 and C38500 architectural brass alloys with stainless internal tie-rods.',
    finish: 'Satin Brushed Brass',
    finishOptions: ['Satin Brushed Brass', 'Mirror Polished Gold', 'Antique Bronze Finish'],
    finishDetails: 'Directional 240-grit satin brushing sealed with clear electrophoretic lacquer.',
    craftTechnique: 'Precision TIG Welding, Milling & Polishing',
    techniqueDetails: 'Seamless silver brazing and hand-buffed joints with invisible fasteners.',
    dimensions: 'Custom tailored per linear meter to project blueprints',
    customDimensions: 'Custom built per linear meter to match architectural drawings.',
    customSize: 'Engineered to stair angle, landings, and balconies',
    customDesign: 'Geometric motif and top cap profile tailored to project specs',
    customFinish: 'Brushed, mirrored, or antique bronze',
    availability: 'custom_only',
    leadTime: 'Custom Quote / 3-5 weeks',
    applications: ['Palaces', 'Villas', 'Hotels', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'bespoke-mashrabiya-brass-staircase-balustrade',
    seoTitle: 'Bespoke Mashrabiya Brass Staircase Balustrade | TURATH Egypt',
    metaDescription: 'Custom architectural brass balustrades and staircase handrails manufactured in Egypt for luxury villas and hotels.',
    seoKeywords: 'brass handrail, brass balustrade, staircase railing, architectural brass, custom metalwork',
    whatsappMessage: 'Hello TURATH, I have an architectural project needing custom brass balustrades (Product ID: TR-RAIL-001). Please get in touch.',
    categoryFields: {
      handrailType: 'Continuous Stair & Balcony Architectural Balustrade',
      profile: 'Molded Solid Brass Ergonomic Oval or Rectangular Cap',
      mounting: 'Floor Core-Drilled Spigots or Side Fascia Mount',
      balusterType: 'Mashrabiya Geometric Infill Panels & Turned Posts',
      projectQuantity: 'Fabricated per linear meter',
      architecturalSpecification: 'CAD shop drawings and site templating support available',
    },
  },

  // 6. Lighting - Heritage Lanterns
  {
    id: 'turath-lantern-01',
    sku: 'TR-LANT-001',
    categoryId: 'lighting',
    name: 'Gamaliya Heritage Hexagonal Brass Lantern (Fanous)',
    nameEN: 'Gamaliya Heritage Hexagonal Brass Lantern (Fanous)',
    nameAR: 'فانوس الجمالية السداسي التراثي من النحاس الخالص',
    tagline: 'Traditional pierced Cairo lantern with hand-blown glass panels',
    shortDescEN: 'Traditional pierced Cairo lantern with hand-blown glass panels',
    shortDescAR: 'فانوس قاهري أصيل مفرغ يدويًا بألواح زجاجية ملونة ومعشقة',
    description: 'Crafted right in Gamaliya street using time-honored artisanal methods. Perforated brass crown and base with intricate floral engraving, ready for hanging or floor placement.',
    fullDescriptionEN: 'Handcrafted in Gamaliya using century-old Cairo copper methods. Features a perforated brass dome crown that vents heat, hand-sawn star perforations, and hand-cut glass panels that cast warm glowing ambient light indoors or on covered verandas.',
    fullDescriptionAR: 'صُنع بأيدي شيوخ الصنعة في قلب حي الجمالية بالقاهرة. يتميز بتاج علوي مفرغ بالنجوم الهندسية وقاعدة سداسية متينة مع زجاج عسلي أو ملون يمنح المكان أجواء رمضانية وتراثية دافئة تدوم لأجيال.',
    story: 'Carrying forward the historic Egyptian Fanous heritage dating back to 969 AD.',
    mainImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Pierced Sheet Brass & Tempered Amber/Clear Glass',
    materialDetails: 'Solid brass sheet, soldered joints, and hand-cut faceted glass panels.',
    finish: 'Vintage Patina Brass',
    finishOptions: ['Vintage Patina Brass', 'Polished Golden Brass', 'Verdigris Aged Green'],
    finishDetails: 'Natural antiqued oxidized finish with clear beeswax sealing.',
    craftTechnique: 'Hand-Cut Openwork & Traditional Soldering',
    techniqueDetails: 'Saw piercing and lead-free tin-silver brazing.',
    dimensions: '85 cm H x 35 cm W (Also available in 120cm and 150cm)',
    height: '85 cm',
    width: '35 cm',
    diameter: '35 cm',
    weight: '6.5 kg',
    customDimensions: 'Available in 50 cm, 85 cm, 120 cm, and 160 cm giant floor models.',
    customSize: 'Multiple standard and giant palace sizes',
    customDesign: 'Glass tint (amber, clear, colored, frosted) customizable',
    customFinish: 'Antique patina, green verdigris, or polished gold',
    availability: 'in_stock',
    leadTime: '7-12 business days',
    applications: ['Homes', 'Villas', 'Hotels', 'Restaurants', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'gamaliya-heritage-hexagonal-brass-lantern',
    seoTitle: 'Gamaliya Heritage Hexagonal Brass Lantern | TURATH Egypt',
    metaDescription: 'Authentic Egyptian pierced brass lantern (Fanous) handcrafted in Cairo with antique patina.',
    seoKeywords: 'Egyptian lantern, brass fanous, Cairo lantern, pierced brass lamp, Islamic lantern',
    whatsappMessage: 'Hello TURATH, I am interested in ordering the Gamaliya Hexagonal Lantern (Product ID: TR-LANT-001). Please send details.',
    categoryFields: {
      lanternType: 'Hanging & Floor Standing Heritage Lantern (Fanous)',
      shape: 'Hexagonal Tapered Column with Pierced Dome',
      pattern: '8-Pointed Islamic Star & Floral Scrollwork',
      perforationStyle: 'Traditional Open Piercing',
      lightSource: 'E27 Socket (Internal Candle or Bulb)',
      bulbType: 'LED Warm Amber 2200K Recommended',
      mounting: 'Heavy brass suspension loop + flat resting base',
      indoorOutdoor: 'Indoor / Covered Terrace & Patio',
      style: 'Traditional Egyptian Fatimid / Mamluk',
    },
  },

  // 7. Wall Cladding
  {
    id: 'turath-cladding-01',
    sku: 'TR-CLD-001',
    categoryId: 'wall-cladding',
    name: 'Fatimid Geometric Pierced & Patinated Brass Wall Cladding Panels',
    nameEN: 'Fatimid Geometric Pierced & Patinated Brass Wall Cladding Panels',
    nameAR: 'تجاليد وكسوة جدران نحاسية هندسية مفرغة ومعتقة - الطراز الفاطمي',
    tagline: 'Modular architectural brass wall panels with integrated backlit shadow diffusion',
    shortDescEN: 'Modular architectural brass wall panels with integrated backlit shadow diffusion',
    shortDescAR: 'ألواح جدارية نحاسية معمارية مفرغة بزخارف هندسية فاطمية معدة للإضاءة الخلفية المخفية',
    description: 'Monumental architectural brass wall cladding designed for luxury hotel lobbies, palace majlis, executive boardrooms, and feature reception backdrops.',
    fullDescriptionEN: 'Monumental architectural brass wall cladding panels engineered for luxury hotel lobbies, palace majlis feature walls, executive backdrops, and private residence atriums. Each modular panel is fabricated from heavy 2.5mm Egyptian brass, laser-profiled and hand-chiseled with Islamic geometric girih patterns, then hand-patinated to achieve warm golden and deep bronze tonal gradients.',
    fullDescriptionAR: 'ألواح كسوة وتجاليد جدران نحاسية معمارية مصممة خصيصًا لمجالس القصور وردهات الفنادق العالمية والمكاتب التنفيذية الكبرى. تُصنع من صفائح النحاس المصري النقي سماكة 2.5 ملم مفرغة بزخارف هندسية فاطمية إسلامية ومعالجة بتعتيق يدوي دافئ يمنح الجدار فخامة معمارية استثنائية عند دمجه مع الإضاءة الخلفية.',
    story: 'Engineered in collaboration with Cairo architectural restorers, celebrating the sacred geometry of medieval Cairo monumental facades.',
    mainImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass & Aged Red Copper',
    materials: 'Solid 2.5mm Egyptian Brass & Copper Sheet, Concealed Aluminum Subframe',
    materialDetails: 'Heavy-gauge architectural grade brass sheet (CuZn37) with interlocking tongue-and-groove perimeter cleats.',
    finish: 'Fire-Patinated Antique Golden Brass',
    finishOptions: ['Fire-Patinated Antique Brass', 'Brushed Satin Champagne Brass', 'Oxidized Dark Bronze', 'Mirror Gold'],
    finishDetails: 'Chemically stabilized patina treated with polyurethane protective coating for high-traffic longevity.',
    craftTechnique: 'Laser-Pierced Filigree & Artisan Hand-Chiseling',
    techniqueDetails: 'Precision CNC laser cutting combined with manual relief embossing and hand-rubbed edge beveling.',
    dimensions: '60 cm W x 120 cm H x 3 cm D per modular panel',
    width: '60 cm',
    height: '120 cm',
    depth: '3 cm',
    weight: '12 kg per panel',
    customDimensions: 'Custom panel sizing engineered to architectural elevation drawings up to 300 cm height.',
    customSize: 'Full custom sizing based on architectural CAD elevation files',
    customDesign: 'Islamic geometric girih, floral mashrabiya, or modern abstract perforations',
    customFinish: 'Antique patina, brushed champagne, deep bronze, or 24K gold plating',
    availability: 'made_to_order',
    leadTime: '20-30 business days',
    applications: ['Hotels', 'Palaces', 'Villas', 'Feature Walls', 'Executive Offices', 'Restaurants'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'fatimid-geometric-pierced-brass-wall-cladding-panels',
    seoTitle: 'Fatimid Geometric Pierced Brass Wall Cladding Panels | TURATH Egypt',
    metaDescription: 'Architectural Egyptian brass wall cladding panels for luxury feature walls, hotel lobbies, and palace majlis.',
    seoKeywords: 'brass wall cladding, architectural brass panels, Islamic geometric screen, decorative metal cladding, Cairo brass',
    whatsappMessage: 'Hello TURATH, I am interested in ordering: Fatimid Geometric Brass Wall Cladding Panels (Product ID: TR-CLD-001). Please provide architectural specifications and pricing.',
    categoryFields: {
      claddingType: 'Modular Architectural Wall Cladding',
      panelPattern: 'Fatimid Geometric Star Girih',
      mountingSystem: 'Concealed Z-Clip Aluminum Hanging Subframe',
      backlightingReady: 'Yes, engineered for LED diffusion backing',
      thickness: '2.5mm solid brass plate',
    },
  },

  // 9. Custom Pieces
  {
    id: 'turath-custom-01',
    sku: 'TR-FAB-001',
    categoryId: 'custom-pieces',
    name: 'Bespoke Hotel Lobby Decorative Room Divider & Screens',
    nameEN: 'Bespoke Hotel Lobby Decorative Room Divider & Screens',
    nameAR: 'قواطع وشاشات الأرابيسك النحاسية المعمارية المخصصة',
    tagline: 'Architectural brass screens manufactured to exact client specs',
    shortDescEN: 'Architectural brass screens manufactured to exact client specs',
    shortDescAR: 'قواطع وديكورات معمارية من النحاس الخالص مصنعة حسب المخططات الهندسية',
    description: 'Turath partners with architects and interior designers to produce fully bespoke brass installations, partition screens, bar cladding, reception desks, and monumental gates.',
    fullDescriptionEN: 'Turath partners directly with architectural firms, hotel operators, and luxury interior studios to fabricate full-scale bespoke metalwork. From laser and waterjet cut screens to hand-hammered bar facades, columns, and monumental gates.',
    fullDescriptionAR: 'تقدم تراث مصر خدمات التصنيع المعماري المخصص لشركات التصميم الداخلي والمعماريين والفنادق الفاخرة. نقوم بتنفيذ القواطع الزخرفية الضخمة، وتجليد واجهات المكاتب ومكاتب الاستقبال، والأبواب والشبابيك التراثية بأعلى معايير الدقة.',
    story: 'Crafted in our specialized Cairo manufacturing facility under the supervision of senior metallurgical engineers.',
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass & Red Copper',
    materials: 'Solid Brass Plate, Extrusions, Tube & Cast Accents',
    materialDetails: 'Industrial grade structural brass alloys with structural sub-framing.',
    finish: 'Custom Architectural Finish',
    finishOptions: ['Any custom finish, patina, satin, mirror, or electroplated tone'],
    finishDetails: 'Matched to architectural material samples provided by client.',
    craftTechnique: 'Laser/Waterjet Cutting, Hand-Finishing & Assembly',
    techniqueDetails: 'CNC cutting paired with artisanal hand deburring, graining, and patination.',
    dimensions: 'Fully custom according to your architectural drawings',
    customDimensions: 'Custom built according to architectural CAD drawings.',
    customSize: 'Full custom dimensions',
    customDesign: 'Full bespoke manufacturing from client drawings or 3D models',
    customFinish: 'PVD, satin, antique, mirror, or verdigris',
    availability: 'custom_only',
    leadTime: 'Varies by project scope',
    applications: ['Hotels', 'Restaurants', 'Palaces', 'Commercial Projects', 'Architectural Projects', 'Offices'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'bespoke-hotel-lobby-brass-screens',
    seoTitle: 'Bespoke Hotel Lobby Decorative Room Divider & Screens | TURATH Egypt',
    metaDescription: 'Custom architectural brass screens, dividers, and bespoke metalwork for commercial and hospitality projects.',
    seoKeywords: 'custom brass fabrication, architectural brass screens, hotel dividers, Cairo bespoke brass, metal fabrication',
    whatsappMessage: 'Hello TURATH, I would like to submit architectural drawings for custom fabrication (Product ID: TR-FAB-001). Please advise next steps.',
    categoryFields: {
      fabricationType: 'Architectural Screens & Partitions',
      subframe: 'Integrated Structural Steel / Heavy Brass Framework',
      tolerances: 'Precision +/- 0.5mm',
    },
  },

  // 10. Decorative Objects
  {
    id: 'turath-accessory-01',
    sku: 'TR-ACC-001',
    categoryId: 'decorative-objects',
    name: 'Royal Gamaliya Incense Burner (Mabkhara)',
    nameEN: 'Royal Gamaliya Incense Burner (Mabkhara)',
    nameAR: 'مبخرة الجمالية الملكية من النحاس المخرّم',
    tagline: 'Traditional brass censer with pierced dome & turned handle',
    shortDescEN: 'Traditional brass censer with pierced dome & turned handle',
    shortDescAR: 'مبخرة نحاسية أصيلة بغطاء قبّة مفرغ ومقبض محفور يدويًا',
    description: 'A cherished fixture of Egyptian hospitality. The domed lid allows fragrant oud and incense smoke to dance gently through hand-pierced star patterns.',
    fullDescriptionEN: 'A cornerstone of Egyptian hospitality and ritual warmth. Crafted from heavy solid brass, the domed lid features hand-sawn star vents that disperse fragrant oud and frankincense smoke in delicate geometric trails, fitted with an insulated wooden turned handle.',
    fullDescriptionAR: 'عنوان الكرم وحسن الضيافة المصرية الأصيلة. صُنعت من النحاس الخالص الثقيل، بغطاء قبّي مفرغ بفتحات نجمية تسمح لدخان العود والبخور بالانتشار بنعومة وهدوء، مع مقبض خشبي مخروط ومقاوم للحرارة.',
    story: 'Preserving the historic fragrance rituals of Old Cairo’s spice markets and royal residences.',
    mainImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Cast & Spun Solid Brass with Heat-Proof Liner',
    materialDetails: 'Solid brass bowl with removable stainless charcoal tray insert.',
    finish: 'Antique Brass',
    finishOptions: ['Antique Brass', 'Bright Gold Brass', 'Dark Bronze'],
    finishDetails: 'Warm antique bronze patina with gold highlight rubbing.',
    craftTechnique: 'Spinning, Piercing & Lathe Turning',
    techniqueDetails: 'Hand spinning, pierce saw-work, and solid lathe turning.',
    dimensions: '32 cm H x 18 cm W',
    height: '32 cm',
    width: '18 cm',
    diameter: '18 cm',
    weight: '2.1 kg',
    customDimensions: 'Available in 25 cm, 32 cm, and 45 cm grand salon sizes.',
    customSize: 'Standard and grand sizes',
    customDesign: 'Monogram or calligraphic engraving on base',
    customFinish: 'Antique, polished gold, or dark bronze',
    availability: 'in_stock',
    leadTime: '5-7 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Interior Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'royal-gamaliya-incense-burner-mabkhara',
    seoTitle: 'Royal Gamaliya Incense Burner (Mabkhara) | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian solid brass incense burner with pierced dome lid for oud and bakhoor.',
    seoKeywords: 'brass mabkhara, incense burner, Egyptian brass censer, oud burner, luxury home accessories',
    whatsappMessage: 'Hello TURATH, I am interested in ordering the Royal Gamaliya Mabkhara (Product ID: TR-ACC-001). Please provide pricing.',
    categoryFields: {
      accessoryType: 'Incense Burner (Mabkhara)',
      liner: 'Removable heat-proof charcoal tray included',
      handle: 'Turned hardwood insulated handle',
    },
  },

  // 11. Vases (Vas)
  {
    id: 'turath-vase-01',
    sku: 'TR-VASE-001',
    categoryId: 'vases',
    name: 'Khan el-Khalili Engraved Brass Floor Amphora',
    nameEN: 'Khan el-Khalili Engraved Brass Floor Amphora',
    nameAR: 'أمفورا وفازة أرضية نحاسية منقوشة - خان الخليلي',
    tagline: 'Tall ornamental floor vase featuring classical floral scrolls',
    shortDescEN: 'Tall ornamental floor vase featuring classical floral scrolls',
    shortDescAR: 'فازة نحاسية أرضية شاهقة منقوشة يدويًا بأجمل الزخارف النباتية الكلاسيكية',
    description: 'Every square centimeter of this grand brass vase is intricately hand-engraved with lotus and palmette motifs by artisans whose lineages date back centuries in old Cairo.',
    fullDescriptionEN: 'A breathtaking ornamental floor amphora hand-spun from heavy gauge Egyptian brass. Covered in thousands of hand-chiseled floral scrolls, lotus leaves, and geometric rosettes, finished with sculpted loop handles and an antique golden patina.',
    fullDescriptionAR: 'فازة أرضية عملاقة تشع بالفخامة، صُنعت يدويًا بالكامل من النحاس الخالص بواسطة أمهر فناني خان الخليلي. تغطي سطحها آلاف النقوش الدقيقة من زهور اللوتس والأرابيسك، مع مقابض مقوسة أنيقة تمنحها هيبة المتاحف الملكية.',
    story: 'Inspired by the ceremonial brass vessels presented to royal ambassadors in 15th-century Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80'
    ],
    material: 'Yellow Brass',
    materials: 'Hand-Spun Heavy Gauge Solid Brass',
    materialDetails: 'Solid brass body spun on giant wooden formers with cast handles.',
    finish: 'Antiqued Gold Brass',
    finishOptions: ['Antiqued Gold Brass', 'Polished High Shine', 'Verdigris Aged Accents'],
    finishDetails: 'Fine-chiseled black oxidation highlighting bright golden raised floral patterns.',
    craftTechnique: 'Manual Spinning, Engraving & Patination',
    techniqueDetails: 'Multi-section metal spinning, silver brazed seams, and steel-burin chisel engraving.',
    dimensions: '95 cm H x 32 cm Max Diameter',
    height: '95 cm',
    width: '32 cm',
    diameter: '32 cm',
    weight: '11.5 kg',
    customDimensions: 'Available from 60 cm up to 180 cm tall monumental vessels.',
    customSize: 'Custom heights available for grand entries',
    customDesign: 'Custom coat of arms or floral density',
    customFinish: 'Antique gold, mirror polish, or verdigris accents',
    availability: 'made_to_order',
    leadTime: '12-16 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'khan-el-khalili-engraved-brass-amphora',
    seoTitle: 'Khan el-Khalili Engraved Brass Floor Amphora | TURATH Egypt',
    metaDescription: 'Monumental hand-engraved Egyptian brass floor vase with classical Islamic scrollwork.',
    seoKeywords: 'brass vase, Egyptian brass amphora, floor vase, Khan el Khalili, handcrafted brass vessel',
    whatsappMessage: 'Hello TURATH, I am interested in the Khan el-Khalili Engraved Floor Amphora (Product ID: TR-VASE-001). Please send quotation.',
    categoryFields: {
      vaseType: 'Monumental Floor Amphora Vase',
      handles: 'Dual Cast Brass Classical Loop Handles',
      waterproof: 'Dry floral arrangement or sealed brass inner vessel',
    },
  },
];
