import { ProductCategoryInfo, ProductItem } from './types';

export const PRODUCT_CATEGORIES: ProductCategoryInfo[] = [
  {
    id: 'brass-mirrors',
    name: 'Brass Mirrors',
    nameArabic: 'مرايا نحاس',
    shortDesc: 'Handcrafted sunburst, arched, and geometric brass mirrors.',
    description: 'Artisanal Egyptian brass framed mirrors combining hand-hammered repoussé techniques, intricate openwork filigree, and polished bevel glass.',
    coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Sparkles',
  },
  {
    id: 'chandeliers',
    name: 'Chandeliers',
    nameArabic: 'نجف وثريات',
    shortDesc: 'Monumental pierced brass chandeliers and hanging pendants.',
    description: 'Sculptural brass chandeliers created for grand halls, palaces, luxury dining spaces, and boutique hotels, casting mesmerizing shadow patterns.',
    coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Flame',
  },
  {
    id: 'wall-lights',
    name: 'Wall Lights (Appliques)',
    nameArabic: 'أبليكات وإضاءة جدارية',
    shortDesc: 'Hand-pierced brass sconces casting warm ambient arabesques.',
    description: 'Artisan brass appliques designed with traditional Gamaliya perforations that transform plain walls into radiant architectural canvases.',
    coverImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Lightbulb',
  },
  {
    id: 'tables-consoles',
    name: 'Tables & Consoles',
    nameArabic: 'طاولات وكونسول نحاس',
    shortDesc: 'Hand-engraved brass coffee tables, dining tables & luxury consoles.',
    description: 'Solid brass structural bases, hand-hammered brass trays, and inlaid consoles paired with marble or tempered glass for timeless living spaces.',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Layers',
  },
  {
    id: 'door-handles',
    name: 'Door Handles',
    nameArabic: 'مقابض أبواب نحاس',
    shortDesc: 'Solid cast brass palace door pulls, levers, and entry hardware.',
    description: 'Heavy architectural door pulls, traditional lion-head knockers, and bespoke forged brass levers that make every entrance unforgettable.',
    coverImage: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Key',
  },
  {
    id: 'handrails',
    name: 'Handrails',
    nameArabic: 'درابزين ودرج نحاسي',
    shortDesc: 'Architectural brass balustrades and custom handrail systems.',
    description: 'Precision-forged brass handrails, spiral balustrades, and geometric brass guardrails designed to client specifications for villas and hotels.',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    iconName: 'ShieldCheck',
  },
  {
    id: 'lanterns',
    name: 'Lanterns',
    nameArabic: 'فوانيس ومصابيح نحاسية',
    shortDesc: 'Historic Cairo pierced brass lanterns and garden fanous.',
    description: 'Authentic Gamaliya hand-cut brass lanterns featuring geometric stars and colored stained glass that create magical, warm atmospheres.',
    coverImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Compass',
  },
  {
    id: 'decorative-wall-art',
    name: 'Decorative Wall Art',
    nameArabic: 'لوحات وجداريات نحاس',
    shortDesc: 'Hand-chiseled medallions, calligraphy panels & 3D reliefs.',
    description: 'Dramatic brass wall sculptures, Quranic calligraphy engravings, and layered geometric panels that celebrate Egypt’s golden decorative legacy.',
    coverImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Palette',
  },
  {
    id: 'custom-brass-fabrication',
    name: 'Custom Brass Fabrication',
    nameArabic: 'تشغيل وتصنيع مخصص',
    shortDesc: 'Bespoke metalwork tailored from your sketches, CAD, or drawings.',
    description: 'Full custom fabrication for architects and interior designers: feature wall screens, bar cladding, decorative canopies, and one-of-a-kind centerpieces.',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Wrench',
  },
  {
    id: 'interior-accessories',
    name: 'Interior Decorative Accessories',
    nameArabic: 'إكسسوارات وديكورات داخلية',
    shortDesc: 'Hand-hammered serving trays (Siniya), burners & decorative accents.',
    description: 'Refined lifestyle pieces including incense burners (Mabkhara), candleholders, brass centerpieces, and etched trays made by master artisans.',
    coverImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Crown',
  },
  {
    id: 'vases',
    name: 'Vas (Vases)',
    nameArabic: 'فازات وأواني نحاسية',
    shortDesc: 'Chiseled brass floor vases, fluted urns, and decorative amphoras.',
    description: 'Hand-spun and hand-engraved Egyptian brass vases featuring classical Islamic patterns and polished gold or dark antique finishes.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
    iconName: 'Wine',
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // 1. Brass Mirrors
  {
    id: 'turath-mirror-01',
    sku: 'TR-MIR-001',
    categoryId: 'brass-mirrors',
    name: 'The Gamaliya Sunburst Brass Mirror',
    nameEN: 'The Gamaliya Sunburst Brass Mirror',
    nameAR: 'مرآة شعاع الشمس النحاسية - الجمالية',
    tagline: 'Hand-chiseled radial petals in antique golden brass',
    shortDescEN: 'Hand-chiseled radial petals in antique golden brass',
    shortDescAR: 'بتلات دائرية منحوتة يدويًا من النحاس الأصفر المعتق',
    description: 'An iconic masterwork handcrafted in Gamaliya, Cairo. Over 48 individually hammered brass rays radiate around a beveled focal mirror, treated with an antique wax patina.',
    fullDescriptionEN: 'An iconic masterwork handcrafted in Gamaliya, Cairo. Over 48 individually hammered brass rays radiate around a beveled focal mirror, treated with an antique wax patina. Inspired by the architectural celestial motifs of historic Fatimid Cairo, each petal is manually textured using steel chisels and annealed over open coals to achieve rich golden depth.',
    fullDescriptionAR: 'تحفة فنية فريدة صُنعت يدويًا في حي الجمالية بالقاهرة التاريخية. أكثر من 48 شعاعًا نحاسيًا مطروقًا يدويًا تتوزع حول مرآة مركزية مشطوفة الحواف معالجة بطبقة شمعية عتيقة. مستوحاة من الزخارف الفاطمية التراثية، حيث يتم نقش كل بتلة بأزاميل فولاذية وتعتيقها بدرجات النحاس الذهبي الدافئ.',
    story: 'Forged in the shadow of Bab Zuweila by generational coppersmiths whose lineage preserves the Fatimid repoussé chiseling traditions.',
    mainImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/n51TrE7f17I',
    material: 'Yellow Brass',
    materials: 'Solid High-Grade Egyptian Yellow Brass, Beveled Glass Mirror',
    materialDetails: 'Heavy-gauge solid brass sheets (grade CuZn37) combined with 6mm Belgian beveled glass.',
    finish: 'Antique Patina Brass',
    finishOptions: ['Antique Brass', 'Polished Gold Brass', 'Dark Verdigris Patina'],
    finishDetails: 'Hand-rubbed jewelers wax over fire-patinated brass.',
    craftTechnique: 'Chased Repoussé & Hand-Polishing',
    techniqueDetails: 'Individual petal repoussé chasing, silver-soldered ring frame, and micro-bevel mirror mounting.',
    dimensions: '110 cm Diameter x 6 cm Depth',
    diameter: '110 cm',
    depth: '6 cm',
    weight: '14.5 kg',
    customDimensions: 'Available from 80 cm up to 200 cm custom diameter.',
    customSize: 'Full custom sizing on request',
    customDesign: 'Ray count, inner medallion etching, and frame profile customizable',
    customFinish: 'Custom matte, antique, or 24K gold electroplated finish',
    availability: 'made_to_order',
    leadTime: '10-14 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'gamaliya-sunburst-brass-mirror',
    seoTitle: 'The Gamaliya Sunburst Brass Mirror | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian sunburst brass mirror featuring 48 individually chiseled brass petals and beveled mirror glass.',
    seoKeywords: 'brass mirror, sunburst mirror, Egyptian brass, Gamaliya, luxury mirror, handcrafted metalwork',
    whatsappMessage: 'Hello TURATH, I am interested in ordering: The Gamaliya Sunburst Brass Mirror (Product ID: TR-MIR-001). Please provide pricing and technical specifications.',
    categoryFields: {
      mirrorType: 'Sunburst Wall Mirror',
      mirrorShape: 'Round',
      frameMaterial: 'Solid Yellow Brass',
      frameTechnique: 'Hand-chiseled Repoussé',
      glassType: '6mm Clear Beveled Glass',
      mounting: 'Heavy-duty wall cleat included',
      orientation: 'Universal Round',
    },
  },
  {
    id: 'turath-mirror-02',
    sku: 'TR-MIR-002',
    categoryId: 'brass-mirrors',
    name: 'Mamluk Arched Mihrab Mirror',
    nameEN: 'Mamluk Arched Mihrab Mirror',
    nameAR: 'مرآة المحراب المملوكي المقوسة',
    tagline: 'Pierced filigree crest with Islamic horseshoe arch',
    shortDescEN: 'Pierced filigree crest with Islamic horseshoe arch',
    shortDescAR: 'تاج مفرغ بدقة الأرابيسك مع قوس حدوة الحصان المملوكي',
    description: 'Inspired by the historic palaces of Al-Mu’izz street. The top arch features intricate pierced brass arabesques that gently filter lighting above the mirror glass.',
    fullDescriptionEN: 'Inspired by the historic palaces of Al-Mu’izz street. The top arch features intricate pierced brass arabesques that gently filter lighting above the mirror glass. Constructed with a heavy structural brass border and reinforced backing for monumental salon or entryway presence.',
    fullDescriptionAR: 'مستوحاة من قصور شارع المعز التاريخية. يتميز التاج العلوي بزخارف نباتية وهندسية إسلامية مفرغة يدويًا تسمح بنفاذ الضوء بنعومة، مع إطار نحاسي متين وهيكل مدعم ومناسب لمداخل الفلل والقصور وصالونات الاستقبال الفخمة.',
    story: 'Recreated from archival drawings of 14th-century Mamluk mosque portals in historic Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/ytBFnWnjw7Q',
    material: 'Yellow Brass',
    materials: 'Solid 2mm Pierced Brass Plate, Antiqued Backing',
    materialDetails: '2.5mm solid brass plate with hand-sawn openwork crest.',
    finish: 'Aged Patina Brass',
    finishOptions: ['Antique Patina', 'Brushed Satin Gold', 'Burnished Bronze'],
    finishDetails: 'Chemically aged verdigris shadow tone with bright brass crest highlights.',
    craftTechnique: 'Openwork Piercing & Acid-Etched Borders',
    techniqueDetails: 'Pierced fretwork sawed by hand using jeweler bow-saws.',
    dimensions: '140 cm H x 80 cm W x 4 cm D',
    height: '140 cm',
    width: '80 cm',
    depth: '4 cm',
    weight: '18 kg',
    customDimensions: 'Custom heights available up to 260 cm for grand hotel foyers.',
    customSize: 'Custom dimensions available',
    customDesign: 'Arch geometry and calligraphy band customization available',
    customFinish: 'Bronze, satin, antique, or polished',
    availability: 'made_to_order',
    leadTime: '14-18 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Offices'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'mamluk-arched-mihrab-mirror',
    seoTitle: 'Mamluk Arched Mihrab Mirror | TURATH Egypt',
    metaDescription: 'Luxury Mamluk arched mirror with hand-pierced Islamic filigree crest in antique brass.',
    seoKeywords: 'Mamluk mirror, arched mirror, Islamic brass, Cairo filigree, handcrafted mirror',
    whatsappMessage: 'Hello TURATH, I am interested in ordering: Mamluk Arched Mihrab Mirror (Product ID: TR-MIR-002). Please provide quotation.',
    categoryFields: {
      mirrorType: 'Arched Vanity & Hallway Mirror',
      mirrorShape: 'Mihrab Horseshoe Arch',
      frameMaterial: 'Solid Brass Plate & Tube',
      frameTechnique: 'Hand-Pierced Openwork Arabesque',
      glassType: '5mm High Clarity Float Mirror',
      mounting: 'Double concealed z-bar wall brackets',
      orientation: 'Vertical Wall Mount',
    },
  },

  // 2. Chandeliers
  {
    id: 'turath-chandelier-01',
    sku: 'TR-CHND-001',
    categoryId: 'chandeliers',
    name: 'Sultan Hassan Monumental Pierced Chandelier',
    nameEN: 'Sultan Hassan Monumental Pierced Chandelier',
    nameAR: 'ثريا السلطان حسن المعمارية المخرمة',
    tagline: 'Multi-tier grand chandelier casting hypnotic star shadows',
    shortDescEN: 'Multi-tier grand chandelier casting hypnotic star shadows',
    shortDescAR: 'ثريا فخمة متعددة المستويات تعكس ظلالاً نجمية ساحرة',
    description: 'A breathtaking centerpiece designed for double-height entrances, palace salons, and boutique hotel lobbies. Tens of thousands of microscopic hand-punched perforations emit warm amber ambient light.',
    fullDescriptionEN: 'A monumental centerpiece designed for double-height entrances, palace salons, and luxury hotel lobbies. Tens of thousands of microscopic hand-punched perforations cast intricate arabesque shadow patterns across ceilings and walls, transforming the surrounding space into an ambient sanctuary.',
    fullDescriptionAR: 'تحفة إضاءة معمارية عملاقة مخصصة للمداخل المرتفعة وصالات القصور وبهو الفنادق الراقية. عشرات الآلاف من الثقوب الدقيقة المنقوشة يدويًا تعكس ظلالاً هندسية ساحرة وتمنح المكان أجواء دافئة مفعمة بالفخامة المصرية الأصيلة.',
    story: 'Modeled after the pierced brass oil lamps that hung in Cairo’s 14th-century Sultan Hassan Mosque.',
    mainImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/BZfrYIp30lU',
    material: 'Yellow Brass',
    materials: 'Pure Heavy Egyptian Brass, Internal Warm LED Chandelier Cluster',
    materialDetails: 'Solid spun and rolled brass cones joined with internal steel suspension skeleton.',
    finish: 'Antique Burnished Brass',
    finishOptions: ['Antique Burnished Brass', 'Champagne Gold', 'Aged Oxidized Dark Brass'],
    finishDetails: 'Multi-stage acid burnishing and hand-waxed sealing.',
    craftTechnique: 'Hand-Pierced Perforated Brass (Mashrabiya Style)',
    techniqueDetails: 'Pierced with custom tempered steel punch needles, one perforation at a time.',
    dimensions: '180 cm H x 120 cm W (Custom sizing available)',
    height: '180 cm',
    width: '120 cm',
    diameter: '120 cm',
    weight: '38 kg',
    customDimensions: 'Custom diameters from 80 cm up to 300 cm available.',
    customSize: 'Tailored dimensions and drop heights available',
    customDesign: 'Tier configuration and pattern density tailored to architects blueprints',
    customFinish: 'Antique bronze, satin champagne, or polished mirror gold',
    availability: 'made_to_order',
    leadTime: '3-4 weeks',
    applications: ['Palaces', 'Villas', 'Hotels', 'Restaurants', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'sultan-hassan-monumental-chandelier',
    seoTitle: 'Sultan Hassan Monumental Pierced Chandelier | TURATH Egypt',
    metaDescription: 'Monumental Egyptian pierced brass chandelier creating 360-degree star shadows for luxury hospitality and villas.',
    seoKeywords: 'pierced brass chandelier, Islamic chandelier, Sultan Hassan, Cairo lighting, luxury lighting',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Sultan Hassan Monumental Chandelier (Product ID: TR-CHND-001). Please send catalog specs and quotation.',
    categoryFields: {
      chandelierType: 'Multi-Tier Pierced Pendant Chandelier',
      numberOfLights: '12 Lights (E27 Standard / LED Compatible)',
      bulbType: 'Warm White LED 2700K',
      voltage: '110V - 240V Universal',
      wattage: 'Max 60W per socket',
      bulbIncluded: true,
      suspensionType: 'Reinforced Solid Brass Heavy Link Chain & Ceiling Rose',
      suspensionLength: 'Adjustable up to 250 cm',
    },
  },
  {
    id: 'turath-chandelier-02',
    sku: 'TR-CHND-002',
    categoryId: 'chandeliers',
    name: 'Nile Lotus Pendant Chandelier',
    nameEN: 'Nile Lotus Pendant Chandelier',
    nameAR: 'ثريا لوتس النيل المتدلية',
    tagline: 'Contemporary brass dome with traditional chased interior',
    shortDescEN: 'Contemporary brass dome with traditional chased interior',
    shortDescAR: 'قبة نحاسية معاصرة مع باطن ذهبي مطروق يدويًا',
    description: 'Sleek brushed brass exterior with a richly hand-hammered gold leaf interior that provides exceptional warm downward task and mood illumination.',
    fullDescriptionEN: 'A master balance of clean modern architectural form and ancient Egyptian craftsmanship. The sleek spun brass outer shell contrasts with a dazzling interior chiseled and gold-leaf patinated to reflect warm downward illumination.',
    fullDescriptionAR: 'توازن ساحر بين التصميم المعماري المعاصر وأصالة الحرفة المصرية القديمة. هيكل خارجي أنيق مصقول بعناية يقابله تجويف داخلي مطروق يدويًا يعكس إضاءة ذهبية دافئة ومثالية لطاولات الطعام والجلسات الراقية.',
    story: 'Inspired by the sacred lotus bud rising from the Nile river, celebrated in Egyptian art for millennia.',
    mainImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/bO9CdCvTsKI',
    material: 'Yellow Brass',
    materials: 'Spun Brass Shell, Chased Golden Interior',
    materialDetails: 'Spun from single 3mm brass disc on historic Cairo metal lathes.',
    finish: 'Brushed Satin Gold',
    finishOptions: ['Two-Tone Matte Black & Gold Brass', 'Solid Polished Brass', 'Warm Antique Brass'],
    finishDetails: 'Brushed exterior with hand-dimpled gold luster interior.',
    craftTechnique: 'Metal Spinning & Chasing',
    techniqueDetails: 'Heavy spinning lathe shaping followed by thousands of ball-peen hammer strikes.',
    dimensions: '75 cm Diameter x 45 cm H',
    diameter: '75 cm',
    height: '45 cm',
    weight: '9.2 kg',
    customDimensions: 'Diameters from 40 cm to 110 cm available.',
    customSize: 'Single or cluster configurations available',
    customDesign: 'Custom outer finishes (black patina, brushed brass, verdigris)',
    customFinish: 'Custom finish options available',
    availability: 'in_stock',
    leadTime: '10-12 business days',
    applications: ['Homes', 'Villas', 'Restaurants', 'Hotels', 'Offices', 'Interior Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'nile-lotus-pendant-chandelier',
    seoTitle: 'Nile Lotus Pendant Chandelier | TURATH Egypt',
    metaDescription: 'Modern spun brass pendant chandelier with hand-chased interior gold leaf reflection.',
    seoKeywords: 'brass pendant, lotus chandelier, dining light, Egyptian brass fixture, luxury pendant',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Nile Lotus Pendant (Product ID: TR-CHND-002). Please send quote.',
    categoryFields: {
      chandelierType: 'Single Dome Pendant Light',
      numberOfLights: '3 Cluster Sockets (E27)',
      bulbType: 'Warm White LED Filament',
      voltage: '110V - 240V',
      wattage: 'Max 40W per socket',
      bulbIncluded: true,
      suspensionType: 'Fabric Braided Cable & Solid Brass Rod',
      suspensionLength: '150 cm adjustable cord',
    },
  },

  // 3. Wall Lights (Appliques)
  {
    id: 'turath-applique-01',
    sku: 'TR-APPL-001',
    categoryId: 'wall-lights',
    name: 'Arabesque Lattice Shadow Sconce',
    nameEN: 'Arabesque Lattice Shadow Sconce',
    nameAR: 'أبليك الشبيكة الأرابيسك الجداري',
    tagline: 'Wall applique with 360-degree geometric shadow projection',
    shortDescEN: 'Wall applique with 360-degree geometric shadow projection',
    shortDescAR: 'أبليك جداري يعكس ظلالاً هندسية ثلاثية الأبعاد بزاوية 360 درجة',
    description: 'Mounted flush against the wall, this brass applique transforms hallways and living spaces into living geometric art installations when lit.',
    fullDescriptionEN: 'Mounted flush against the wall, this brass applique transforms corridors, salons, and suite entrances into radiant architectural displays. Precision hand-pierced arabesques project crisp geometric shadows across the wall surface.',
    fullDescriptionAR: 'يتم تركيبه مستويًا على الحائط ليحوّل الممرات والغرف إلى لوحة فنية ضوئية متكاملة. النقوش الأرابيسكية المفرغة يدويًا تعكس خطوطًا ضوئية هندسية ساحرة على الجدران تضفي دفئًا وأناقة لا مثيل لها.',
    story: 'Designed after the Mashrabiya window lattices of Beit El Suhaymi in historic Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/w3BWw9WM3Cw',
    material: 'Yellow Brass',
    materials: 'Cut Brass Plate with Concealed Warm Sconce Socket (E27)',
    materialDetails: 'Solid brass curved shield with concealed aluminum mounting base.',
    finish: 'Antique Brass',
    finishOptions: ['Antique Brass', 'Raw Polished Gold', 'Hammered Patina'],
    finishDetails: 'Aged brass patina with sealed lacquer protectant.',
    craftTechnique: 'Pierced Geometric Filigree',
    techniqueDetails: 'Micro-pierced openwork using traditional Gamaliya hand saws.',
    dimensions: '60 cm H x 25 cm W x 14 cm D',
    height: '60 cm',
    width: '25 cm',
    depth: '14 cm',
    weight: '3.8 kg',
    customDimensions: 'Available in heights from 40 cm to 120 cm.',
    customSize: 'Custom size options available',
    customDesign: 'Pattern motif and projection angle customized for projects',
    customFinish: 'Satin gold, bronze, or aged verdigris',
    availability: 'in_stock',
    leadTime: '7-10 business days',
    applications: ['Homes', 'Villas', 'Hotels', 'Restaurants', 'Commercial Projects', 'Hospitality'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'arabesque-lattice-shadow-sconce',
    seoTitle: 'Arabesque Lattice Shadow Sconce | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian brass wall light sconce casting intricate arabesque shadows on walls.',
    seoKeywords: 'brass wall sconce, applique, Egyptian lighting, wall light, arabesque lighting',
    whatsappMessage: 'Hello TURATH, I would like to order the Arabesque Lattice Shadow Sconce (Product ID: TR-APPL-001). Please send pricing.',
    categoryFields: {
      lightType: 'Wall Applique / Sconce',
      numberOfBulbs: 1,
      bulbType: 'E27 Filament Bulb (Warm Amber)',
      lightDirection: 'Omnidirectional Wall Wash & Pierced Shadow Projection',
      projection: '14 cm from wall',
      lightingEffect: '360° Geometric Arabesque Shadow Cast',
    },
  },

  // 4. Tables & Consoles
  {
    id: 'turath-table-01',
    sku: 'TR-TAB-001',
    categoryId: 'tables-consoles',
    name: 'Al-Azhar Hexagonal Brass Coffee Table',
    nameEN: 'Al-Azhar Hexagonal Brass Coffee Table',
    nameAR: 'طاولة القهوة السداسية النحاسية - الأزهر',
    tagline: 'Hand-engraved tray top resting on carved brass arch base',
    shortDescEN: 'Hand-engraved tray top resting on carved brass arch base',
    shortDescAR: 'صينية نحاسية منقوشة يدويًا تستند إلى قاعدة أقواس إسلامية سداسية',
    description: 'A statement coffee table featuring an authentic removable brass tray (siniya) intricately engraved with 8-fold Islamic rosettes, seated upon a solid brass interlocking base.',
    fullDescriptionEN: 'A statement coffee table featuring an authentic removable heavy brass tray (siniya) intricately hand-chiseled with 8-fold Islamic rosettes and calligraphic medallions, resting upon an interlocking solid brass arched leg base.',
    fullDescriptionAR: 'طاولة قهوة فاخرة تجمع بين صينية نحاسية ثقيلة قابلة للرفع منقوشة يدويًا بأشكال الزهور الهندسية والزخارف الإسلامية، وقاعدة نحاسية سداسية تتألف من أقواس معمارية مفرغة تمنح الغرفة طابع الفخامة الملكية.',
    story: 'Inspired by the historic Mamluk brass trays crafted for Al-Azhar courtyards and royal salons.',
    mainImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/5K2c6HpTh3Q',
    material: 'Yellow Brass',
    materials: 'Heavy Gauge Solid Brass Sheet & Cast Base',
    materialDetails: 'Solid 3.5mm thick tray sheet with cast brass mortise-and-tenon leg structure.',
    finish: 'Antiqued Gold Brass',
    finishOptions: ['Antiqued Gold Brass', 'Satin Brushed Brass', 'Two-Tone Pewter & Brass'],
    finishDetails: 'Acid-etched background with polished raised relief surfaces.',
    craftTechnique: 'Hand-Engraving & Solid Metal Joinery',
    techniqueDetails: 'Engraved with hardened steel burins over weeks of artisan hand labor.',
    dimensions: '90 cm Diameter x 48 cm H',
    diameter: '90 cm',
    height: '48 cm',
    weight: '22 kg',
    customDimensions: 'Custom diameters from 60 cm to 140 cm.',
    customSize: 'Custom diameters and heights available',
    customDesign: 'Center medallion and leg arches customizable',
    customFinish: 'Antique, satin brushed, or two-tone',
    availability: 'made_to_order',
    leadTime: '15-20 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'al-azhar-hexagonal-brass-coffee-table',
    seoTitle: 'Al-Azhar Hexagonal Brass Coffee Table | TURATH Egypt',
    metaDescription: 'Hand-engraved Egyptian brass tray table with solid arched brass base for luxury living rooms.',
    seoKeywords: 'brass coffee table, Egyptian tray table, siniya table, Islamic furniture, luxury brass table',
    whatsappMessage: 'Hello TURATH, I am interested in the Al-Azhar Hexagonal Coffee Table (Product ID: TR-TAB-001). Please provide pricing details.',
    categoryFields: {
      tableType: 'Coffee Table / Tea Table',
      shape: 'Hexagonal / Round Tray',
      topMaterial: 'Hand-Engraved Heavy Brass Siniya',
      baseMaterial: 'Interlocking Cast & Pierced Brass Arches',
      glassMarbleType: 'Optional tempered protective glass top available',
    },
  },

  // 5. Door Handles
  {
    id: 'turath-doorhandle-01',
    sku: 'TR-HDL-001',
    categoryId: 'door-handles',
    name: 'Imperial Palace Lion Head Solid Brass Pull',
    nameEN: 'Imperial Palace Lion Head Solid Brass Pull',
    nameAR: 'مقبض قصر الرئاسة برأس الأسد من النحاس الصب',
    tagline: 'Heavy sand-cast architectural entrance handle',
    shortDescEN: 'Heavy sand-cast architectural entrance handle',
    shortDescAR: 'مقبض مدخل رئيسي فاخر مصبوب من النحاس الخالص برأس أسد بارز',
    description: 'Weighing over 4.5 kilograms of solid cast brass, this statement handle is inspired by historic Egyptian palace portals. Features tactile detailed relief and durable weather-resistant wax finish.',
    fullDescriptionEN: 'Weighing over 4.5 kilograms of solid sand-cast brass, this monumental pull is designed for luxury villa and palace main entrance portals. Featuring high-relief lion head symbolism and a hand-turned reeded gripping bar with concealed through-bolt mounting.',
    fullDescriptionAR: 'يزن المقبض أكثر من 4.5 كيلوجرام من النحاس المصبوب الصلب، وهو مصمم خصيصًا لمداخل القصور والفلل الفاخرة. يتميز بنقوش بارزة ثلاثية الأبعاد تمثل رأس الأسد الملكي مع مقبض محزز مريح لليد وتثبيت مخفي قوي ومقاوم للعوامل الجوية.',
    story: 'Cast using traditional sand-molding techniques practiced in Cairo foundry alleys since Mamluk times.',
    mainImage: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/sQq7NwddpyE',
    material: 'Yellow Brass',
    materials: 'Solid Cast Egyptian Brass Alloy',
    materialDetails: 'High-density sand-cast brass alloy with high copper content for weather resistance.',
    finish: 'Aged Antique Patina',
    finishOptions: ['Aged Antique Patina', 'Polished High-Luster Brass', 'Matte Architectural Bronze'],
    finishDetails: 'Thermal wax immersion for exterior weather protection.',
    craftTechnique: 'Sand-Casting & Hand-Chiseling',
    techniqueDetails: 'Sand molding, molten brass pouring, followed by hand chasing of mane details.',
    dimensions: '45 cm Length x 12 cm Width',
    height: '45 cm',
    width: '12 cm',
    depth: '9 cm',
    weight: '4.8 kg',
    customDimensions: 'Custom lengths from 30 cm up to 100 cm available.',
    customSize: 'Single or back-to-back pairs available',
    customDesign: 'Custom escutcheon plates and family crests cast on request',
    customFinish: 'Weatherproof exterior dark bronze or bright gold',
    availability: 'in_stock',
    leadTime: '10 business days',
    applications: ['Palaces', 'Villas', 'Hotels', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'imperial-palace-lion-head-brass-pull',
    seoTitle: 'Imperial Palace Lion Head Solid Brass Pull | TURATH Egypt',
    metaDescription: 'Solid cast brass entrance door handle pull with lion head relief for luxury villas and palaces.',
    seoKeywords: 'brass door pull, palace door handle, lion head handle, Egyptian brass hardware, luxury door pull',
    whatsappMessage: 'Hello TURATH, I am inquiring about the Imperial Lion Head Door Pull (Product ID: TR-HDL-001). Please send quote.',
    categoryFields: {
      handleType: 'Entrance Door Pull Handle (Single or Back-to-Back Pair)',
      doorType: 'Solid Wood, Glass, or Heavy Metal Entrance Doors',
      backplate: 'Integrated Cast Medallion Rosettes',
      mountingType: 'Concealed Through-Bolt Fixings Included',
      lockCompatibility: 'Universal pull - compatible with mortise, deadbolt, or electronic smart locks',
    },
  },

  // 6. Handrails
  {
    id: 'turath-handrail-01',
    sku: 'TR-RAIL-001',
    categoryId: 'handrails',
    name: 'Bespoke Mashrabiya Brass Staircase Balustrade',
    nameEN: 'Bespoke Mashrabiya Brass Staircase Balustrade',
    nameAR: 'درابزين السلالم النحاسي المعماري - شبيكة المشربية',
    tagline: 'Continuous custom-fabricated architectural railing',
    shortDescEN: 'Continuous custom-fabricated architectural railing',
    shortDescAR: 'درابزين سلالم نحاسي معماري متصل بنقوش المشربية الإسلامية',
    description: 'Precision-welded solid brass architectural handrails and balusters featuring classical Islamic geometric patterns for luxury villas, duplexes, and prestigious hotels.',
    fullDescriptionEN: 'Continuous precision-engineered solid brass architectural balustrade system. Features waterjet-cut and hand-finished Mashrabiya geometric infill panels, molded solid brass top-cap profiles, and heavy turned brass newel posts designed to architects exact stair rise and run.',
    fullDescriptionAR: 'نظام درابزين معماري متكامل من النحاس الخالص المخصص للسلالم الداخلية الفاخرة. يجمع بين ألواح الشبيكة الهندسية المقطوعة بدقة والمشطوبة يدويًا، مع مقبض علوي انسيابي وقوائم متينة مصممة بدقة حسب المقاسات الهندسية للمشروع.',
    story: 'Engineered in our Cairo fabrication studio to blend traditional aesthetics with modern architectural safety codes.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/rwMpDPEFbLw',
    material: 'Yellow Brass',
    materials: 'Architectural Brass Box Profiles, Flat Bars & Turned Newel Posts',
    materialDetails: 'C36000 and C38500 architectural brass alloys with stainless internal tie-rods.',
    finish: 'Satin Brushed Brass',
    finishOptions: ['Satin Brushed Brass', 'Mirror Polished Gold', 'Antique Bronze Finish'],
    finishDetails: 'Directional 240-grit satin brushing sealed with clear electrophoretic lacquer.',
    craftTechnique: 'Precision TIG Welding, Milling & Polishing',
    techniqueDetails: 'Seamless silver brazing and hand-buffed joints with invisible fasteners.',
    dimensions: 'Custom tailored per linear meter to project blueprints',
    customDimensions: 'Custom built per linear meter to match architectural drawings.',
    customSize: 'Engineered to stair angle, landings, and balconies',
    customDesign: 'Geometric motif and top cap profile tailored to project specs',
    customFinish: 'Brushed, mirrored, or antique bronze',
    availability: 'custom_only',
    leadTime: 'Custom Quote / 3-5 weeks',
    applications: ['Palaces', 'Villas', 'Hotels', 'Commercial Projects', 'Architectural Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'bespoke-mashrabiya-brass-staircase-balustrade',
    seoTitle: 'Bespoke Mashrabiya Brass Staircase Balustrade | TURATH Egypt',
    metaDescription: 'Custom architectural brass balustrades and staircase handrails manufactured in Egypt for luxury villas and hotels.',
    seoKeywords: 'brass handrail, brass balustrade, staircase railing, architectural brass, custom metalwork',
    whatsappMessage: 'Hello TURATH, I have an architectural project needing custom brass balustrades (Product ID: TR-RAIL-001). Please get in touch.',
    categoryFields: {
      handrailType: 'Continuous Stair & Balcony Architectural Balustrade',
      profile: 'Molded Solid Brass Ergonomic Oval or Rectangular Cap',
      mounting: 'Floor Core-Drilled Spigots or Side Fascia Mount',
      balusterType: 'Mashrabiya Geometric Infill Panels & Turned Posts',
      projectQuantity: 'Fabricated per linear meter',
      architecturalSpecification: 'CAD shop drawings and site templating support available',
    },
  },

  // 7. Lanterns
  {
    id: 'turath-lantern-01',
    sku: 'TR-LANT-001',
    categoryId: 'lanterns',
    name: 'Gamaliya Heritage Hexagonal Brass Lantern (Fanous)',
    nameEN: 'Gamaliya Heritage Hexagonal Brass Lantern (Fanous)',
    nameAR: 'فانوس الجمالية السداسي التراثي من النحاس الخالص',
    tagline: 'Traditional pierced Cairo lantern with hand-blown glass panels',
    shortDescEN: 'Traditional pierced Cairo lantern with hand-blown glass panels',
    shortDescAR: 'فانوس قاهري أصيل مفرغ يدويًا بألواح زجاجية ملونة ومعشقة',
    description: 'Crafted right in Gamaliya street using time-honored artisanal methods. Perforated brass crown and base with intricate floral engraving, ready for hanging or floor placement.',
    fullDescriptionEN: 'Handcrafted in Gamaliya using century-old Cairo copper methods. Features a perforated brass dome crown that vents heat, hand-sawn star perforations, and hand-cut glass panels that cast warm glowing ambient light indoors or on covered verandas.',
    fullDescriptionAR: 'صُنع بأيدي شيوخ الصنعة في قلب حي الجمالية بالقاهرة. يتميز بتاج علوي مفرغ بالنجوم الهندسية وقاعدة سداسية متينة مع زجاج عسلي أو ملون يمنح المكان أجواء رمضانية وتراثية دافئة تدوم لأجيال.',
    story: 'Carrying forward the historic Egyptian Fanous heritage dating back to 969 AD.',
    mainImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/Okz_6g4kopQ',
    material: 'Yellow Brass',
    materials: 'Pierced Sheet Brass & Tempered Amber/Clear Glass',
    materialDetails: 'Solid brass sheet, soldered joints, and hand-cut faceted glass panels.',
    finish: 'Vintage Patina Brass',
    finishOptions: ['Vintage Patina Brass', 'Polished Golden Brass', 'Verdigris Aged Green'],
    finishDetails: 'Natural antiqued oxidized finish with clear beeswax sealing.',
    craftTechnique: 'Hand-Cut Openwork & Traditional Soldering',
    techniqueDetails: 'Saw piercing and lead-free tin-silver brazing.',
    dimensions: '85 cm H x 35 cm W (Also available in 120cm and 150cm)',
    height: '85 cm',
    width: '35 cm',
    diameter: '35 cm',
    weight: '6.5 kg',
    customDimensions: 'Available in 50 cm, 85 cm, 120 cm, and 160 cm giant floor models.',
    customSize: 'Multiple standard and giant palace sizes',
    customDesign: 'Glass tint (amber, clear, colored, frosted) customizable',
    customFinish: 'Antique patina, green verdigris, or polished gold',
    availability: 'in_stock',
    leadTime: '7-12 business days',
    applications: ['Homes', 'Villas', 'Hotels', 'Restaurants', 'Hospitality', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'gamaliya-heritage-hexagonal-brass-lantern',
    seoTitle: 'Gamaliya Heritage Hexagonal Brass Lantern | TURATH Egypt',
    metaDescription: 'Authentic Egyptian pierced brass lantern (Fanous) handcrafted in Cairo with antique patina.',
    seoKeywords: 'Egyptian lantern, brass fanous, Cairo lantern, pierced brass lamp, Islamic lantern',
    whatsappMessage: 'Hello TURATH, I am interested in ordering the Gamaliya Hexagonal Lantern (Product ID: TR-LANT-001). Please send details.',
    categoryFields: {
      lanternType: 'Hanging & Floor Standing Heritage Lantern (Fanous)',
      shape: 'Hexagonal Tapered Column with Pierced Dome',
      pattern: '8-Pointed Islamic Star & Floral Scrollwork',
      perforationStyle: 'Traditional Open Piercing',
      lightSource: 'E27 Socket (Internal Candle or Bulb)',
      bulbType: 'LED Warm Amber 2200K Recommended',
      mounting: 'Heavy brass suspension loop + flat resting base',
      indoorOutdoor: 'Indoor / Covered Terrace & Patio',
      style: 'Traditional Egyptian Fatimid / Mamluk',
    },
  },

  // 8. Decorative Wall Art
  {
    id: 'turath-wallart-01',
    sku: 'TR-ART-001',
    categoryId: 'decorative-wall-art',
    name: 'Al-Fath Islamic Calligraphy Brass Medallion',
    nameEN: 'Al-Fath Islamic Calligraphy Brass Medallion',
    nameAR: 'جدارية نحاسية منقوشة - سورة الفتح بخط الثلث الجلي',
    tagline: 'Hand-chiseled Arabic calligraphy in deep 3D brass relief',
    shortDescEN: 'Hand-chiseled Arabic calligraphy in deep 3D brass relief',
    shortDescAR: 'لوحة جدارية دائرية منقوشة بأجمل آيات الخط العربي البارز ثلاثي الأبعاد',
    description: 'A majestic 100 cm circular brass wall plaque engraved by master Egyptian calligraphers with verses of blessing and victory, framed by concentric geometric arabesque bands.',
    fullDescriptionEN: 'A majestic 100 cm circular solid brass wall plaque created by master Egyptian calligraphers and metalsmiths. Features deep repoussé Arabic calligraphy in classical Thuluth script, flanked by intricate interlaced geometric borders.',
    fullDescriptionAR: 'جدارية نحاسية دائرية مهيبة بقطر 100 سم من النحاس الخالص. نُقشت بأيدي كبار خطاطي القاهرة التاريخية بحروف بارزة ثلاثية الأبعاد تنبض بالحياة، محاطة بأشرطة هندسية ونباتية بديعة تعكس روعة الفن الإسلامي الخالد.',
    story: 'Drawn freehand by certified Al-Azhar master calligraphers before being hammered in brass.',
    mainImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/Necs3R1rkXg',
    material: 'Yellow Brass',
    materials: 'Solid 3mm Hand-Hammered Brass Plate',
    materialDetails: 'Solid 3mm thick brass plate mounted to rigid black composite acoustic backing.',
    finish: 'Oxidized Dark Patina with Polished Raised Letters',
    finishOptions: ['Oxidized Dark Patina with Polished Raised Letters', 'Monochrome Gold Brass', 'Matte Brushed Brass'],
    finishDetails: 'Two-tone contrast: darkened recessed background with gleaming golden letters.',
    craftTechnique: 'Hand-Chiseled Repoussé Relief',
    techniqueDetails: 'Pitch-bowl repoussé chasing with precision chasing punches.',
    dimensions: '100 cm Diameter x 3 cm Depth',
    diameter: '100 cm',
    depth: '3 cm',
    weight: '12 kg',
    customDimensions: 'Custom diameters from 70 cm up to 220 cm.',
    customSize: 'Custom scale for reception and boardroom walls',
    customDesign: 'Custom Quranic verses, poetry, or company logos available',
    customFinish: 'Two-tone antique, pure 24K gold gilding, or monochrome gold',
    availability: 'made_to_order',
    leadTime: '14-20 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Offices', 'Hotels', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'al-fath-islamic-calligraphy-brass-medallion',
    seoTitle: 'Al-Fath Islamic Calligraphy Brass Medallion | TURATH Egypt',
    metaDescription: 'Hand-chiseled Arabic calligraphy brass wall art plaque in deep 3D relief for luxury interiors.',
    seoKeywords: 'Arabic calligraphy art, brass wall art, Islamic metal art, Egyptian brass plaque, luxury wall decor',
    whatsappMessage: 'Hello TURATH, I am inquiring regarding the Al-Fath Calligraphy Plaque (Product ID: TR-ART-001). Please send quote.',
    categoryFields: {
      wallArtType: 'Circular 3D Calligraphy Medallion',
      scriptStyle: 'Thuluth Jali Script',
      frameMaterial: 'Concentric Hand-Engraved Brass Ring',
      mounting: 'Heavy-duty wall bracket included',
    },
  },

  // 9. Custom Brass Fabrication
  {
    id: 'turath-custom-01',
    sku: 'TR-FAB-001',
    categoryId: 'custom-brass-fabrication',
    name: 'Bespoke Hotel Lobby Decorative Room Divider & Screens',
    nameEN: 'Bespoke Hotel Lobby Decorative Room Divider & Screens',
    nameAR: 'قواطع وشاشات الأرابيسك النحاسية المعمارية المخصصة',
    tagline: 'Architectural brass screens manufactured to exact client specs',
    shortDescEN: 'Architectural brass screens manufactured to exact client specs',
    shortDescAR: 'قواطع وديكورات معمارية من النحاس الخالص مصنعة حسب المخططات الهندسية',
    description: 'Turath partners with architects and interior designers to produce fully bespoke brass installations, partition screens, bar cladding, reception desks, and monumental gates.',
    fullDescriptionEN: 'Turath partners directly with architectural firms, hotel operators, and luxury interior studios to fabricate full-scale bespoke metalwork. From laser and waterjet cut screens to hand-hammered bar facades, columns, and monumental gates.',
    fullDescriptionAR: 'تقدم تراث مصر خدمات التصنيع المعماري المخصص لشركات التصميم الداخلي والمعماريين والفنادق الفاخرة. نقوم بتنفيذ القواطع الزخرفية الضخمة، وتجليد واجهات المكاتب ومكاتب الاستقبال، والأبواب والشبابيك التراثية بأعلى معايير الدقة.',
    story: 'Crafted in our specialized Cairo manufacturing facility under the supervision of senior metallurgical engineers.',
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/1-YlwfgvZCU',
    material: 'Yellow Brass & Red Copper',
    materials: 'Solid Brass Plate, Extrusions, Tube & Cast Accents',
    materialDetails: 'Industrial grade structural brass alloys with structural sub-framing.',
    finish: 'Custom Architectural Finish',
    finishOptions: ['Any custom finish, patina, satin, mirror, or electroplated tone'],
    finishDetails: 'Matched to architectural material samples provided by client.',
    craftTechnique: 'Laser/Waterjet Cutting, Hand-Finishing & Assembly',
    techniqueDetails: 'CNC cutting paired with artisanal hand deburring, graining, and patination.',
    dimensions: 'Fully custom according to your architectural drawings',
    customDimensions: 'Custom built according to architectural CAD drawings.',
    customSize: 'Full custom dimensions',
    customDesign: 'Full bespoke manufacturing from client drawings or 3D models',
    customFinish: 'PVD, satin, antique, mirror, or verdigris',
    availability: 'custom_only',
    leadTime: 'Varies by project scope',
    applications: ['Hotels', 'Restaurants', 'Palaces', 'Commercial Projects', 'Architectural Projects', 'Offices'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'bespoke-hotel-lobby-brass-screens',
    seoTitle: 'Bespoke Hotel Lobby Decorative Room Divider & Screens | TURATH Egypt',
    metaDescription: 'Custom architectural brass screens, dividers, and bespoke metalwork for commercial and hospitality projects.',
    seoKeywords: 'custom brass fabrication, architectural brass screens, hotel dividers, Cairo bespoke brass, metal fabrication',
    whatsappMessage: 'Hello TURATH, I would like to submit architectural drawings for custom fabrication (Product ID: TR-FAB-001). Please advise next steps.',
    categoryFields: {
      fabricationType: 'Architectural Screens & Partitions',
      subframe: 'Integrated Structural Steel / Heavy Brass Framework',
      tolerances: 'Precision +/- 0.5mm',
    },
  },

  // 10. Interior Decorative Accessories
  {
    id: 'turath-accessory-01',
    sku: 'TR-ACC-001',
    categoryId: 'interior-accessories',
    name: 'Royal Gamaliya Incense Burner (Mabkhara)',
    nameEN: 'Royal Gamaliya Incense Burner (Mabkhara)',
    nameAR: 'مبخرة الجمالية الملكية من النحاس المخرّم',
    tagline: 'Traditional brass censer with pierced dome & turned handle',
    shortDescEN: 'Traditional brass censer with pierced dome & turned handle',
    shortDescAR: 'مبخرة نحاسية أصيلة بغطاء قبّة مفرغ ومقبض محفور يدويًا',
    description: 'A cherished fixture of Egyptian hospitality. The domed lid allows fragrant oud and incense smoke to dance gently through hand-pierced star patterns.',
    fullDescriptionEN: 'A cornerstone of Egyptian hospitality and ritual warmth. Crafted from heavy solid brass, the domed lid features hand-sawn star vents that disperse fragrant oud and frankincense smoke in delicate geometric trails, fitted with an insulated wooden turned handle.',
    fullDescriptionAR: 'عنوان الكرم وحسن الضيافة المصرية الأصيلة. صُنعت من النحاس الخالص الثقيل، بغطاء قبّي مفرغ بفتحات نجمية تسمح لدخان العود والبخور بالانتشار بنعومة وهدوء، مع مقبض خشبي مخروط ومقاوم للحرارة.',
    story: 'Preserving the historic fragrance rituals of Old Cairo’s spice markets and royal residences.',
    mainImage: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/h4AfTz4sO3c',
    material: 'Yellow Brass',
    materials: 'Cast & Spun Solid Brass with Heat-Proof Liner',
    materialDetails: 'Solid brass bowl with removable stainless charcoal tray insert.',
    finish: 'Antique Brass',
    finishOptions: ['Antique Brass', 'Bright Gold Brass', 'Dark Bronze'],
    finishDetails: 'Warm antique bronze patina with gold highlight rubbing.',
    craftTechnique: 'Spinning, Piercing & Lathe Turning',
    techniqueDetails: 'Hand spinning, pierce saw-work, and solid lathe turning.',
    dimensions: '32 cm H x 18 cm W',
    height: '32 cm',
    width: '18 cm',
    diameter: '18 cm',
    weight: '2.1 kg',
    customDimensions: 'Available in 25 cm, 32 cm, and 45 cm grand salon sizes.',
    customSize: 'Standard and grand sizes',
    customDesign: 'Monogram or calligraphic engraving on base',
    customFinish: 'Antique, polished gold, or dark bronze',
    availability: 'in_stock',
    leadTime: '5-7 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Interior Projects'],
    priceType: 'quote',
    featured: false,
    visibility: 'published',
    seoSlug: 'royal-gamaliya-incense-burner-mabkhara',
    seoTitle: 'Royal Gamaliya Incense Burner (Mabkhara) | TURATH Egypt',
    metaDescription: 'Handcrafted Egyptian solid brass incense burner with pierced dome lid for oud and bakhoor.',
    seoKeywords: 'brass mabkhara, incense burner, Egyptian brass censer, oud burner, luxury home accessories',
    whatsappMessage: 'Hello TURATH, I am interested in ordering the Royal Gamaliya Mabkhara (Product ID: TR-ACC-001). Please provide pricing.',
    categoryFields: {
      accessoryType: 'Incense Burner (Mabkhara)',
      liner: 'Removable heat-proof charcoal tray included',
      handle: 'Turned hardwood insulated handle',
    },
  },

  // 11. Vases (Vas)
  {
    id: 'turath-vase-01',
    sku: 'TR-VASE-001',
    categoryId: 'vases',
    name: 'Khan el-Khalili Engraved Brass Floor Amphora',
    nameEN: 'Khan el-Khalili Engraved Brass Floor Amphora',
    nameAR: 'أمفورا وفازة أرضية نحاسية منقوشة - خان الخليلي',
    tagline: 'Tall ornamental floor vase featuring classical floral scrolls',
    shortDescEN: 'Tall ornamental floor vase featuring classical floral scrolls',
    shortDescAR: 'فازة نحاسية أرضية شاهقة منقوشة يدويًا بأجمل الزخارف النباتية الكلاسيكية',
    description: 'Every square centimeter of this grand brass vase is intricately hand-engraved with lotus and palmette motifs by artisans whose lineages date back centuries in old Cairo.',
    fullDescriptionEN: 'A breathtaking ornamental floor amphora hand-spun from heavy gauge Egyptian brass. Covered in thousands of hand-chiseled floral scrolls, lotus leaves, and geometric rosettes, finished with sculpted loop handles and an antique golden patina.',
    fullDescriptionAR: 'فازة أرضية عملاقة تشع بالفخامة، صُنعت يدويًا بالكامل من النحاس الخالص بواسطة أمهر فناني خان الخليلي. تغطي سطحها آلاف النقوش الدقيقة من زهور اللوتس والأرابيسك، مع مقابض مقوسة أنيقة تمنحها هيبة المتاحف الملكية.',
    story: 'Inspired by the ceremonial brass vessels presented to royal ambassadors in 15th-century Cairo.',
    mainImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80'
    ],
    videoUrl: 'https://www.youtube-nocookie.com/embed/uLn_xl0VUR4',
    material: 'Yellow Brass',
    materials: 'Hand-Spun Heavy Gauge Solid Brass',
    materialDetails: 'Solid brass body spun on giant wooden formers with cast handles.',
    finish: 'Antiqued Gold Brass',
    finishOptions: ['Antiqued Gold Brass', 'Polished High Shine', 'Verdigris Aged Accents'],
    finishDetails: 'Fine-chiseled black oxidation highlighting bright golden raised floral patterns.',
    craftTechnique: 'Manual Spinning, Engraving & Patination',
    techniqueDetails: 'Multi-section metal spinning, silver brazed seams, and steel-burin chisel engraving.',
    dimensions: '95 cm H x 32 cm Max Diameter',
    height: '95 cm',
    width: '32 cm',
    diameter: '32 cm',
    weight: '11.5 kg',
    customDimensions: 'Available from 60 cm up to 180 cm tall monumental vessels.',
    customSize: 'Custom heights available for grand entries',
    customDesign: 'Custom coat of arms or floral density',
    customFinish: 'Antique gold, mirror polish, or verdigris accents',
    availability: 'made_to_order',
    leadTime: '12-16 business days',
    applications: ['Homes', 'Villas', 'Palaces', 'Hotels', 'Interior Projects'],
    priceType: 'quote',
    featured: true,
    visibility: 'published',
    seoSlug: 'khan-el-khalili-engraved-brass-amphora',
    seoTitle: 'Khan el-Khalili Engraved Brass Floor Amphora | TURATH Egypt',
    metaDescription: 'Monumental hand-engraved Egyptian brass floor vase with classical Islamic scrollwork.',
    seoKeywords: 'brass vase, Egyptian brass amphora, floor vase, Khan el Khalili, handcrafted brass vessel',
    whatsappMessage: 'Hello TURATH, I am interested in the Khan el-Khalili Engraved Floor Amphora (Product ID: TR-VASE-001). Please send quotation.',
    categoryFields: {
      vaseType: 'Monumental Floor Amphora Vase',
      handles: 'Dual Cast Brass Classical Loop Handles',
      waterproof: 'Dry floral arrangement or sealed brass inner vessel',
    },
  },
];
